"""
Build the detailed basemap layers for the v2 map from public-domain data.

Inputs (downloaded into pipeline/basemap/cache/, which git ignores):
  US Census Bureau cartographic boundary file, counties 1:500,000 (2023):
    https://www2.census.gov/geo/tiger/GENZ2023/kml/cb_2023_us_county_500k.zip
  Natural Earth 1:10m (public domain), from github.com/nvkelso/natural-earth-vector:
    geojson/ne_10m_admin_0_countries.geojson        land outside the US, national borders
    geojson/ne_10m_admin_1_states_provinces_lines.geojson   Canadian and Mexican province/state lines
    geojson/ne_10m_lakes*.geojson                   lakes (global + North America + Europe)
    geojson/ne_10m_rivers*.geojson                  rivers (global + North America + Europe)
  US Census Bureau gazetteer of places (2023): towns
    https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2023_Gazetteer/2023_Gaz_place_national.zip

Output (v2/basemap/):
  index.js                 BASEMAP_INDEX: the zoom bands, tile size and which tiles exist
  detail_<band>_<tx>_<ty>.js   one tile: BASEMAP_TILE(band, tx, ty, {layer: [shape, ...]})
                           layers: land, lakes (filled rings); coast, border, seam,
                           state, county, rivers (lines). Each shape is a flat list
                           [x0, y0, dx, dy, ...] in units of `quant`.
  towns.js                 BASEMAP_TOWNS: [name, state, x, y], most prominent first

How it works
  * Everything is converted to the page's projected units: x = lon + 35,
    y = 65 - lat (the map's plain equirectangular projection).
  * Topology: county (and country) outlines are split into arcs at the
    points where three or more meet, so every shared border is one arc,
    stored once. An arc used by one county is coast (or the national land
    border); by two counties of one state, a county line; by two states, a
    state line. Because each arc is simplified once and reused by both
    neighbours, simplified polygons still fit together with no cracks.
  * Each zoom band simplifies (Douglas-Peucker) to about half a screen pixel
    at the band's lowest zoom, and groups features into grid cells so the
    page draws only what is on screen.
  * The US comes from the Census counties (1:500,000, clipped to the
    shoreline, so the Chesapeake and tidewater rivers are sharp); the rest
    of the world from Natural Earth countries, with the US removed.

Pure Python 3 standard library. Usage:
  python pipeline/basemap/build_basemap.py [--check]
"""
import json, math, re, sys, time, zipfile, pathlib, csv, io
import xml.etree.ElementTree as ET
from collections import defaultdict

HERE = pathlib.Path(__file__).resolve().parent
CACHE = HERE / 'cache'
OUT = HERE.parent.parent / 'v2' / 'basemap'

# Area kept: generous around everything the map shows (the old basemap
# spans lon -168..63, lat 2..84).
LON0, LON1, LAT0, LAT1 = -170.0, 70.0, -10.0, 85.0
QUANT = 1e-4          # output grid, projected units (~11 m); smaller than any drawn detail

# Zoom bands. The page shows band 1 from zoom 3.5, band 2 from 10, band 3
# from 30. Tolerance ~0.6 px at the band's lowest zoom: at zoom k one map
# unit is about 12.2 * k CSS px on a 1500 px wide map.
LEVELS = {   # tile: grid size in map units; a screenful is ~123/k x 60/k units at zoom k
    1: dict(min_zoom=3.5, tol=0.6 / (12.2 * 3.5), tile=16.0, rivers_max_rank=7),
    2: dict(min_zoom=10, tol=0.6 / (12.2 * 10), tile=6.0, rivers_max_rank=99),
    3: dict(min_zoom=30, tol=0.6 / (12.2 * 30), tile=2.0, rivers_max_rank=99),
}
HEADER = ('// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau\n'
          '// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).\n')
# Natural Earth is 1:10m; below this tolerance there is nothing left to gain
NE_MIN_TOL = 0.004


def proj(lon, lat):
    x = lon + 35.0
    if x >= 180.0: x -= 360.0
    if x < -180.0: x += 360.0
    return (x, 65.0 - lat)


def log(*a):
    print(f'[{time.strftime("%H:%M:%S")}]', *a, flush=True)


# ---------------------------------------------------------------- readers
def clean_ring(pts):
    """Drop consecutive duplicates and the closing point; None if degenerate."""
    out = []
    for p in pts:
        if not out or p != out[-1]:
            out.append(p)
    if len(out) > 1 and out[0] == out[-1]:
        out.pop()
    return out if len(out) >= 3 else None


def read_counties():
    """[(owner, statefp, is_outer, ring)], rings as lists of (lon, lat) in source order."""
    z = zipfile.ZipFile(CACHE / 'cb_2023_us_county_500k.zip')
    ns = '{http://www.opengis.net/kml/2.2}'
    polys = []
    with z.open('cb_2023_us_county_500k.kml') as f:
        for ev, el in ET.iterparse(f):
            if el.tag != ns + 'Placemark':
                continue
            data = {d.get('name'): d.text for d in el.iter(ns + 'SimpleData')}
            geoid, st = data['GEOID'], data['STATEFP']
            for poly in el.iter(ns + 'Polygon'):
                for tag, outer in (('outerBoundaryIs', True), ('innerBoundaryIs', False)):
                    for b in poly.iter(ns + tag):
                        for c in b.iter(ns + 'coordinates'):
                            pts = []
                            for tok in c.text.split():
                                v = tok.split(',')
                                pts.append((float(v[0]), float(v[1])))
                            # drop what lies outside the kept area (Aleutians
                            # past the antimeridian, Guam, American Samoa...)
                            if not all(LON0 <= p[0] <= -60 and LAT0 <= p[1] <= LAT1 for p in pts):
                                continue
                            r = clean_ring(pts)
                            if r: polys.append((geoid, st, outer, r))
            el.clear()
    return polys


def geojson(name):
    return json.load(open(CACHE / f'{name}.geojson', encoding='utf-8'))['features']


def geom_polys(g):
    """GeoJSON (Multi)Polygon -> [(is_outer, ring)]"""
    if g is None: return []
    polys = g['coordinates'] if g['type'] == 'MultiPolygon' else [g['coordinates']]
    out = []
    for poly in polys:
        for i, ring in enumerate(poly):
            out.append((i == 0, [tuple(p[:2]) for p in ring]))
    return out


def geom_lines(g):
    if g is None: return []
    if g['type'] == 'LineString': return [[tuple(p[:2]) for p in g['coordinates']]]
    if g['type'] == 'MultiLineString': return [[tuple(p[:2]) for p in l] for l in g['coordinates']]
    return []


def clip_ring_box(ring, x0, y0, x1, y1):
    """Sutherland-Hodgman clip of a closed ring to a box (lon/lat)."""
    def clip(pts, inside, cut):
        out = []
        n = len(pts)
        for i in range(n):
            a, b = pts[i - 1], pts[i]
            ia, ib = inside(a), inside(b)
            if ib:
                if not ia: out.append(cut(a, b))
                out.append(b)
            elif ia:
                out.append(cut(a, b))
        return out
    def cx(v):
        return lambda a, b: (v, a[1] + (b[1] - a[1]) * (v - a[0]) / (b[0] - a[0]))
    def cy(v):
        return lambda a, b: (a[0] + (b[0] - a[0]) * (v - a[1]) / (b[1] - a[1]), v)
    pts = ring
    for inside, cut in ((lambda p: p[0] >= x0, cx(x0)), (lambda p: p[0] <= x1, cx(x1)),
                        (lambda p: p[1] >= y0, cy(y0)), (lambda p: p[1] <= y1, cy(y1))):
        if not pts: break
        pts = clip(pts, inside, cut)
    return pts


def clip_line_box(line, x0, y0, x1, y1):
    """Keep the runs of a polyline whose points lie inside the box (rivers: good enough)."""
    runs, cur = [], []
    for p in line:
        if x0 <= p[0] <= x1 and y0 <= p[1] <= y1:
            cur.append(p)
        else:
            if len(cur) >= 2: runs.append(cur)
            cur = []
    if len(cur) >= 2: runs.append(cur)
    return runs


# ---------------------------------------------------------------- topology
def build_topology(polys):
    """polys: [(owner, is_outer, ring)]. Returns (arcs, rings):
    arcs  = list of point lists (each shared border once), with arc_owners[i] = [owner, ...]
    rings = [(owner, is_outer, [(arc_id, reversed), ...])]"""
    nbr = defaultdict(set)
    for _, _, r in polys:
        n = len(r)
        for i in range(n):
            a, b = r[i], r[(i + 1) % n]
            nbr[a].add(b); nbr[b].add(a)
    junction = {p for p, s in nbr.items() if len(s) != 2}
    arc_index, arcs, arc_owners, rings = {}, [], [], []

    def canon(seq):
        # the same border walked either way, or (closed) from any start, is one arc
        if seq[0] == seq[-1]:           # closed: rotate to its smallest point
            body = seq[:-1]
            k = min(range(len(body)), key=body.__getitem__)
            fwd = body[k:] + body[:k]
            rev = list(reversed(fwd)); rev = rev[-1:] + rev[:-1]
            f, r = tuple(fwd + fwd[:1]), tuple(rev + rev[:1])
        else:
            f, r = tuple(seq), tuple(reversed(seq))
        return (f, False) if f <= r else (r, True)

    for owner, outer, r in polys:
        n = len(r)
        js = [i for i in range(n) if r[i] in junction]
        if not js:
            pieces = [r + r[:1]]
        else:
            s = js[0]
            rot = r[s:] + r[:s]
            cut = [i for i in range(n) if rot[i] in junction] + [n]
            rot = rot + rot[:1]
            pieces = [rot[cut[k]:cut[k + 1] + 1] for k in range(len(cut) - 1)]
        refs = []
        for seq in pieces:
            key, rev = canon(seq)
            aid = arc_index.get(key)
            if aid is None:
                aid = arc_index[key] = len(arcs)
                arcs.append(list(key)); arc_owners.append([])
            arc_owners[aid].append(owner)
            refs.append((aid, rev))
        rings.append((owner, outer, refs))
    return arcs, arc_owners, rings


# ---------------------------------------------------------------- simplify
def dp(pts, tol):
    """Douglas-Peucker, endpoints kept. pts in projected units."""
    n = len(pts)
    if n <= 2: return pts[:]
    keep = [False] * n
    keep[0] = keep[-1] = True
    stack = [(0, n - 1)]
    t2 = tol * tol
    while stack:
        a, b = stack.pop()
        ax, ay = pts[a]; bx, by = pts[b]
        dx, dy = bx - ax, by - ay
        L2 = dx * dx + dy * dy
        best, bi = -1.0, -1
        for i in range(a + 1, b):
            px, py = pts[i]
            if L2 == 0:
                d = (px - ax) ** 2 + (py - ay) ** 2
            else:
                t = ((px - ax) * dx + (py - ay) * dy) / L2
                t = 0 if t < 0 else 1 if t > 1 else t
                d = (px - ax - t * dx) ** 2 + (py - ay - t * dy) ** 2
            if d > best: best, bi = d, i
        if best > t2:
            keep[bi] = True
            stack.append((a, bi)); stack.append((bi, b))
    return [p for p, k in zip(pts, keep) if k]


def simplify_arc(pts, tol):
    if pts[0] == pts[-1] and len(pts) > 3:
        # closed arc: split at the point farthest from the start so both halves keep shape
        far = max(range(len(pts)), key=lambda i: (pts[i][0] - pts[0][0]) ** 2 + (pts[i][1] - pts[0][1]) ** 2)
        return dp(pts[:far + 1], tol)[:-1] + dp(pts[far:], tol)
    return dp(pts, tol)


def ring_from_arcs(refs, sarcs):
    out = []
    for aid, rev in refs:
        a = sarcs[aid]
        if rev: a = a[::-1]
        out.extend(a if not out else a[1:])
    if len(out) > 1 and out[0] == out[-1]: out.pop()
    return out


def signed_area(r):
    s = 0.0
    for i in range(len(r)):
        x1, y1 = r[i - 1]; x2, y2 = r[i]
        s += x1 * y2 - x2 * y1
    return s / 2


def bbox(pts):
    xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
    return (min(xs), min(ys), max(xs), max(ys))


def union_rings(rings, sarcs, arcs, skip_owner=None, stats=None):
    """Outline of the union of polygons: chain the arcs that belong to only
    one included polygon, each walked the way its (normalised) polygon walks
    it, so outer outlines come out counter-clockwise and holes clockwise --
    without the thousands of internal county borders a fill doesn't need.
    Each polygon's direction comes from its full-detail outline (`arcs`): a
    tiny polygon simplified to a sliver can flip, which would break chains."""
    use = defaultdict(int)
    for owner, outer, refs in rings:
        if owner != skip_owner:
            for aid, _ in refs: use[aid] += 1
    directed = []
    for owner, outer, refs in rings:
        if owner == skip_owner: continue
        r = ring_from_arcs(refs, arcs)
        flip = len(r) >= 3 and (signed_area(r) > 0) != outer
        for aid, rev in (reversed(refs) if flip else refs):
            if use[aid] == 1:
                a = sarcs[aid]
                directed.append(a[::-1] if (rev != flip) else a)
    starts = defaultdict(list)
    for i, a in enumerate(directed): starts[a[0]].append(i)
    used, out = [False] * len(directed), []
    for i in range(len(directed)):
        if used[i]: continue
        used[i] = True
        ring = directed[i][:]
        while ring[-1] != ring[0]:
            nxt = next((j for j in starts.get(ring[-1], ()) if not used[j]), None)
            if nxt is None: break
            used[nxt] = True
            ring.extend(directed[nxt][1:])
        if ring[0] != ring[-1]:
            # an outline that doesn't close would be filled wrongly: leave it out, and count it
            if stats is not None: stats['open'] = stats.get('open', 0) + 1
            continue
        ring.pop()
        if len(ring) >= 3: out.append(ring)
    return out


def clip_line_to_box(line, x0, y0, x1, y1):
    """Liang-Barsky per segment; returns the runs of the polyline inside the box."""
    runs, cur = [], []
    for a, b in zip(line, line[1:]):
        dx, dy = b[0] - a[0], b[1] - a[1]
        t0, t1 = 0.0, 1.0
        ok = True
        for p, qv in ((-dx, a[0] - x0), (dx, x1 - a[0]), (-dy, a[1] - y0), (dy, y1 - a[1])):
            if p == 0:
                if qv < 0: ok = False; break
            else:
                t = qv / p
                if p < 0:
                    if t > t1: ok = False; break
                    if t > t0: t0 = t
                else:
                    if t < t0: ok = False; break
                    if t < t1: t1 = t
        if not ok:
            if len(cur) >= 2: runs.append(cur)
            cur = []
            continue
        pa = (a[0] + t0 * dx, a[1] + t0 * dy) if t0 > 0 else a
        pb = (a[0] + t1 * dx, a[1] + t1 * dy) if t1 < 1 else b
        if cur and cur[-1] == pa:
            cur.append(pb)
        else:
            if len(cur) >= 2: runs.append(cur)
            cur = [pa, pb]
        if t1 < 1:
            runs.append(cur); cur = []
    if len(cur) >= 2: runs.append(cur)
    return runs


# ---------------------------------------------------------------- land borders
class SegIndex:
    """Grid index of line segments, for 'is this point near that line?'"""
    def __init__(self, lines, cell=0.25):
        self.cell, self.g = cell, defaultdict(list)
        for l in lines:
            for a, b in zip(l, l[1:]):
                x0, x1 = sorted((a[0], b[0])); y0, y1 = sorted((a[1], b[1]))
                for gx in range(int(math.floor(x0 / cell)), int(math.floor(x1 / cell)) + 1):
                    for gy in range(int(math.floor(y0 / cell)), int(math.floor(y1 / cell)) + 1):
                        self.g[(gx, gy)].append((a, b))
    def near(self, p, d):
        c = self.cell
        gx, gy = int(math.floor(p[0] / c)), int(math.floor(p[1] / c))
        d2 = d * d
        for i in (-1, 0, 1):
            for j in (-1, 0, 1):
                for a, b in self.g.get((gx + i, gy + j), ()):
                    dx, dy = b[0] - a[0], b[1] - a[1]
                    L2 = dx * dx + dy * dy
                    t = 0 if L2 == 0 else max(0, min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / L2))
                    ex, ey = a[0] + t * dx - p[0], a[1] + t * dy - p[1]
                    if ex * ex + ey * ey <= d2: return True
        return False


# ---------------------------------------------------------------- output
def q(v): return int(round(v / QUANT))


def encode(pts):
    """[x0, y0, dx, dy, ...] in QUANT units -- short JSON, exact on decode."""
    out, px, py = [], 0, 0
    for i, (x, y) in enumerate(pts):
        ix, iy = q(x), q(y)
        if i and ix == px and iy == py: continue
        out.extend((ix, iy) if i == 0 else (ix - px, iy - py))
        px, py = ix, iy
    return out


def main():
    t0 = time.time()
    OUT.mkdir(parents=True, exist_ok=True)

    # ---- US counties (Census 1:500k), projected
    log('reading counties')
    counties = read_counties()
    state_of = {}
    cpolys = []
    for geoid, st, outer, r in counties:
        state_of[geoid] = st
        cpolys.append((geoid, outer, [proj(*p) for p in r]))
    log(f'  {len(cpolys)} rings, {sum(len(r) for _, _, r in cpolys)} points')
    carcs, cown, crings = build_topology(cpolys)
    log(f'  {len(carcs)} arcs')

    # ---- Natural Earth countries (incl. USA for topology, so its land borders are known)
    log('reading countries')
    npolys = []
    for f in geojson('ne_10m_admin_0_countries'):
        a3 = f['properties']['ADM0_A3']
        for outer, r in geom_polys(f['geometry']):
            r = clip_ring_box(r, LON0, LAT0, LON1, LAT1)
            r = clean_ring(r) if r else None
            if r: npolys.append((a3, outer, [proj(*p) for p in r]))
    narcs, nown, nrings = build_topology(npolys)
    log(f'  {len(npolys)} rings, {len(narcs)} arcs')
    X0, Y0 = proj(LON0, LAT1); X1, Y1 = proj(LON1, LAT0)
    def on_box(arc):   # arc runs along the clipping box: not a real coast
        return all(abs(p[0] - X0) < 1e-9 or abs(p[0] - X1) < 1e-9 or abs(p[1] - Y0) < 1e-9 or abs(p[1] - Y1) < 1e-9 for p in arc)
    us_border = [a for a, o in zip(narcs, nown) if 'USA' in o and len(set(o)) == 2]
    log(f'  {len(us_border)} Natural Earth arcs on the US land border')
    border_idx = SegIndex(us_border)

    # classify county boundary arcs: land border (near NE's US border) vs coast
    ckind = []
    for a, o in zip(carcs, cown):
        if len(o) >= 2:
            ckind.append('state' if state_of[o[0]] != state_of[o[1]] else 'county')
        else:
            step = max(1, len(a) // 20)
            near = sum(border_idx.near(p, 0.08) for p in a[::step])
            ckind.append('border' if near * 2 > len(a[::step]) else 'coast')
    nkind = []
    for a, o in zip(narcs, nown):
        s = set(o)
        if 'USA' in s: nkind.append('us' if len(s) == 1 else 'usborder')
        elif len(o) >= 2: nkind.append('border')
        else: nkind.append('box' if on_box(a) else 'coast')

    # ---- Canada / Mexico province and state lines
    prov = []
    for f in geojson('ne_10m_admin_1_states_provinces_lines'):
        p = f['properties']
        if p['ADM0_A3'] in ('CAN', 'MEX') and p['FEATURECLA'] == 'Admin-1 boundary':
            for l in geom_lines(f['geometry']):
                for run in clip_line_box(l, LON0, LAT0, LON1, LAT1):
                    prov.append([proj(*pt) for pt in run])

    # ---- lakes and rivers (global + regional supplements, deduplicated)
    lakes, seen = [], set()
    for name in ('ne_10m_lakes', 'ne_10m_lakes_north_america', 'ne_10m_lakes_europe'):
        for f in geojson(name):
            key = f['properties'].get('ne_id') or id(f)
            if key in seen: continue
            seen.add(key)
            for outer, r in geom_polys(f['geometry']):
                if not all(LON0 <= p[0] <= LON1 and LAT0 <= p[1] <= LAT1 for p in r): continue
                r = clean_ring(r)
                if r: lakes.append((outer, [proj(*p) for p in r]))
    rivers, seen = [], set()
    for name in ('ne_10m_rivers_lake_centerlines', 'ne_10m_rivers_north_america', 'ne_10m_rivers_europe'):
        for f in geojson(name):
            p = f['properties']
            key = p.get('ne_id') or id(f)
            if key in seen: continue
            seen.add(key)
            rank = p.get('scalerank') if p.get('scalerank') is not None else 99
            for l in geom_lines(f['geometry']):
                for run in clip_line_box(l, LON0, LAT0, LON1, LAT1):
                    rivers.append((rank, [proj(*pt) for pt in run]))
    log(f'  {len(lakes)} lake rings, {len(rivers)} river lines, {len(prov)} province lines')
    # lakes get topology too: Natural Earth splits some (the Great Lakes at
    # the Straits of Mackinac and along the international boundary), and
    # only a lake's real shore should be outlined, not the seams between pieces
    # (the regional files also repeat some lakes under other ids). With every
    # lake walked the same way round, a seam between two pieces is walked once
    # each way (the uses cancel), while a real shore -- even one that appears
    # in two overlapping copies -- is walked one way only.
    larcs, lown, lrings = build_topology([(i, outer, r) for i, (outer, r) in enumerate(lakes)])
    lnet = defaultdict(int)
    for _, outer, refs in lrings:
        flip = (signed_area(ring_from_arcs(refs, larcs)) > 0) != outer
        for aid, rev in refs: lnet[aid] += -1 if (rev != flip) else 1

    # ---- per zoom band: simplify, then cut into tiles (one small file each)
    X0, Y0 = proj(LON0, LAT1)
    X1, Y1 = proj(LON1, LAT0)
    index = {'quant': QUANT, 'levels': {}}
    for old in OUT.glob('detail_*.js'): old.unlink()
    for lv, cfg in LEVELS.items():
        tol = cfg['tol']
        ntol = max(tol, NE_MIN_TOL)
        sc = [simplify_arc(a, tol) for a in carcs]
        sn = [simplify_arc(a, ntol) for a in narcs]
        min_extent = tol * 3
        polys = defaultdict(list)   # layer -> rings (closed, oriented)
        lines = defaultdict(list)   # layer -> polylines

        def keep_ring(r):
            if len(r) < 3: return False
            bb = bbox(r)
            return (bb[2] - bb[0]) >= min_extent or (bb[3] - bb[1]) >= min_extent

        # land: outline of the union of the US counties, plus the union of the
        # other countries (the US left out); outer rings counter-clockwise and
        # holes clockwise, so the page can fill with the nonzero rule
        stats = {}
        land = union_rings(crings, sc, carcs, stats=stats) + union_rings(nrings, sn, narcs, skip_owner='USA', stats=stats)
        if stats.get('open'): log(f'  WARNING: {stats["open"]} land outlines did not close and were left out')
        polys['land'] = [r for r in land if keep_ring(r)]
        for a, k in zip(sc, ckind):
            lines[k].append(a)
        for a, k in zip(sn, nkind):
            if k == 'coast': lines['coast'].append(a)
            elif k == 'border': lines['border'].append(a)
            elif k == 'usborder': lines['seam'].append(a)   # land-coloured band closing gaps where the two datasets meet
        for l in prov:
            lines['state'].append(dp(l, ntol))
        sl = [simplify_arc(a, ntol) for a in larcs]
        for owner, outer, refs in lrings:
            s = ring_from_arcs(refs, sl)
            if keep_ring(s):
                if (signed_area(ring_from_arcs(refs, larcs)) > 0) != outer: s = s[::-1]
                polys['lakes'].append(s)
        for aid, a in enumerate(sl):
            if lnet[aid] != 0: lines['lakeEdge'].append(a)
        for rank, l in rivers:
            if rank <= cfg['rivers_max_rank']:
                lines['rivers'].append(dp(l, ntol))

        # tiles: clip everything to a grid; the page loads the tiles on screen
        T = cfg['tile']
        tiles = defaultdict(lambda: defaultdict(list))
        def tile_range(bb):
            return (range(math.floor(bb[0] / T), math.floor(bb[2] / T) + 1),
                    range(math.floor(bb[1] / T), math.floor(bb[3] / T) + 1))
        for layer, rs in polys.items():
            for r in rs:
                txs, tys = tile_range(bbox(r))
                for tx in txs:
                    for ty in tys:
                        box = (tx * T, ty * T, (tx + 1) * T, (ty + 1) * T)
                        c = clip_ring_box(r, *box)
                        c = clean_ring(c) if c else None
                        if c and abs(signed_area(c)) > 0:
                            tiles[(tx, ty)][layer].append(encode(c))
        for layer, ls in lines.items():
            for l in ls:
                if len(l) < 2: continue
                txs, tys = tile_range(bbox(l))
                for tx in txs:
                    for ty in tys:
                        box = (tx * T, ty * T, (tx + 1) * T, (ty + 1) * T)
                        for run in clip_line_to_box(l, *box):
                            e = encode(run)
                            if len(e) >= 4: tiles[(tx, ty)][layer].append(e)
        total, npts = 0, defaultdict(int)
        for (tx, ty), layers in sorted(tiles.items()):
            payload = {k: v for k, v in sorted(layers.items())}
            for k, v in payload.items(): npts[k] += sum(len(e) // 2 for e in v)
            js = (HEADER + f'BASEMAP_TILE({lv},{tx},{ty},' + json.dumps(payload, separators=(',', ':')) + ');\n')
            p = OUT / f'detail_{lv}_{tx}_{ty}.js'
            p.write_text(js, encoding='utf-8', newline='\n')
            total += p.stat().st_size
        index['levels'][lv] = {'minZoom': cfg['min_zoom'], 'tile': T,
                               'tiles': sorted(f'{tx},{ty}' for tx, ty in tiles)}
        log(f'level {lv}: {len(tiles)} tiles, {total // 1024} KB total, '
            f'largest {max((OUT / f"detail_{lv}_{tx}_{ty}.js").stat().st_size for tx, ty in tiles) // 1024} KB; points {dict(npts)}')
    (OUT / 'index.js').write_text(HEADER + 'window.BASEMAP_INDEX = ' + json.dumps(index, separators=(',', ':')) + ';\n',
                                  encoding='utf-8', newline='\n')

    # ---- towns (Census gazetteer): name, position, and a size rank for label priority
    log('towns')
    z = zipfile.ZipFile(CACHE / '2023_Gaz_place_national.zip')
    text = z.read(z.namelist()[0]).decode('utf-8', errors='replace')
    rows = list(csv.DictReader(io.StringIO(text), delimiter='\t'))
    SUFFIX = re.compile(r' (city and borough|consolidated government.*|metropolitan government.*|unified government.*|'
                        r'urban county|city|town|village|borough|CDP|municipality|comunidad|zona urbana)( \(balance\))?$')
    towns = []
    for r in rows:
        r = {k.strip(): (v or '').strip() for k, v in r.items()}
        lat, lon = float(r['INTPTLAT']), float(r['INTPTLONG'])
        if not (LON0 <= lon <= -60 and LAT0 <= lat <= LAT1): continue
        name = SUFFIX.sub('', r['NAME'])
        incorporated = r['FUNCSTAT'] in ('A', 'B', 'C', 'G')   # active legal governments vs statistical (CDP)
        x, y = proj(lon, lat)
        towns.append((0 if incorporated else 1, -int(r['ALAND'] or 0), name, r['USPS'], round(x, 4), round(y, 4)))
    towns.sort()
    js = ('// Generated by pipeline/basemap/build_basemap.py -- do not edit. Source: US Census Bureau\n'
          '// 2023 gazetteer of places (public domain). [name, state, x, y], most prominent first:\n'
          '// incorporated places before census-designated ones, then by land area.\n'
          'window.BASEMAP_TOWNS = ' + json.dumps([[n, s, x, y] for _, _, n, s, x, y in towns], separators=(',', ':'), ensure_ascii=False) + ';\n')
    (OUT / 'towns.js').write_text(js, encoding='utf-8', newline='\n')
    log(f'towns.js {(OUT / "towns.js").stat().st_size // 1024} KB, {len(towns)} places')
    log(f'done in {time.time() - t0:.0f} s')


if __name__ == '__main__':
    main()
