// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,19,{"county":[[520000,388481,2634,510,1464,486],[532041,386235,1165,471,918,959,1026,837,1001,105,2705,535,1144,259],[524098,389477,838,-319,730,-416,1300,-97,814,-220,1301,-853,461,-513,1086,-511,1413,-313]],"land":[[540000,380000,0,20000,-20000,0,0,-20000]]});
