// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,49,18,{"border":[[980000,377717,38,-5,524,-144,561,0,648,-152,942,550,483,861,-390,-59,-197,76,-295,498,19,658]],"land":[[1000000,360000,0,20000,-20000,0,0,-20000]]});
