// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,18,21,{"border":[[360000,438025,1465,958,128,202,197,815]],"county":[[363016,420000,-15,7299,189,330,500,592,16310,8945]],"land":[[380000,420000,0,20000,-20000,0,0,-20000]]});
