// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,35,-8,{"coast":[[715936,-151588,527,133,1396,57,390,-20,288,-101,-2011,-230,-590,161]],"land":[[715936,-151588,590,-161,2011,230,-288,101,-390,20,-1396,-57]]});
