// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,47,14,{"border":[[950433,280000,56,60,375,640,462,566,1059,1037,211,273,290,613,206,291,331,149,6577,-96]],"land":[[960000,280000,0,20000,-20000,0,0,-20000]],"rivers":[[960000,281382,-20,-16,-224,138,-205,-74,-615,-546,-245,-443,-34,-172,-380,-269]]});
