// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(1,-5,3,{"coast":[[-652635,480000,2718,903,780,825,162,-256,393,14,-186,361,411,132,-224,61,1948,978,2890,303,3743,1066],[-742342,546921,156,263,66,-211,-222,-52]],"land":[[-640000,480000,0,4387,-3743,-1066,-2890,-303,-1948,-978,224,-61,-411,-132,186,-361,-393,-14,-162,256,-780,-825,-2718,-903]]});
