// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-13,37,{"coast":[[-260000,750000,20000,0]],"land":[[-240000,740000,0,10000,-20000,0,0,-10000]],"rivers":[[-256650,740000,61,449,152,-83,105,-234,83,-28,107,100,11,452,282,467,-332,550,-251,201,-19,234,538,875,160,474,301,324,267,749]]});
