// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,40,23,{"border":[[800000,475705,1654,11,567,110,1626,909,457,145,8922,879,3875,-513,371,206,1908,2548]],"land":[[820000,460000,0,20000,-20000,0,0,-20000]]});
