// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,14,11,{"coast":[[883340,704202,107,208,-107,-208],[877419,719943,28,57],[877447,720000,-28,-57]]});
