// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,16,20,{"border":[[320000,411872,12431,8128]],"land":[[340000,400000,0,20000,-20000,0,0,-20000]]});
