// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,10,{"county":[[1049533,217927,-473,-106,-837,-36,-1481,-426,-593,-648,51,-424,-367,-260,-523,-152,224,-308,890,-900,2420,-5263,327,-353,-59,-756,-1065,-4928,-1339,-3367]],"land":[[1040000,220000,0,-20000,10000,0,0,20000]]});
