// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,40,19,{"county":[[807441,380000,297,306,953,811,435,266,647,171,1652,44,879,217,634,324,2467,1590,474,165,459,40],[817829,383694,473,75,216,130,1482,1299],[816338,383934,1491,-240]],"land":[[820000,380000,0,20000,-20000,0,0,-20000]]});
