// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,20,16,{"county":[[415183,320000,1655,4882,436,838,1235,1888,785,967,706,623]],"land":[[420000,320000,0,20000,-20000,0,0,-20000]]});
