// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-39,23,{"coast":[[-760672,462313,141,-473,525,-522,6,3],[-760000,462650,-84,-74,-588,-263]],"land":[[-760672,462313,141,-473,525,-522,6,3,0,1329,-84,-74]]});
