// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,22,19,{"border":[[448108,380000,147,794,96,196,716,435,39,144,-280,1413,137,490,-417,1284,-188,202,-3532,1516,-50,370,-428,436,-570,1031,234,555,5683,7180,384,640,135,634,69,2680]],"land":[[460000,380000,0,20000,-20000,0,0,-20000]]});
