// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,22,{"county":[[820000,455667,6150,-628,1301,-352],[829459,440000,-2008,14687],[826762,460000,689,-5313]],"land":[[840000,440000,0,20000,-20000,0,0,-20000]]});
