// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,31,-8,{"coast":[[620000,-148469,1497,-81,577,-187,317,-318,-142,-194,-903,-303,-325,-192,561,-365,129,-181,-349,-137,266,-240,763,-306,-472,-123,-1880,-56,-39,-14]],"land":[[620000,-151166,39,14,1880,56,472,123,-763,306,-266,240,349,137,-129,181,-561,365,325,192,903,303,142,194,-317,318,-577,187,-1497,81]]});
