// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,47,16,{"border":[[960000,335354,-1450,-181,-333,-120,-117,-937,-174,-717,127,-739,-138,-925,-22,-485,74,-618,-127,-525,86,-220,-177,-159,339,-440,60,-167,135,-795,20,-815,-780,-2457,-1748,-4997,-13,-57]],"county":[[940000,338195,1163,743,848,1062]],"land":[[960000,320000,0,20000,-20000,0,0,-20000]]});
