// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,22,{"county":[[533446,440000,-1939,646,-1977,989,-1236,1235,-1236,248,-2965,0,-495,2718,-3598,6336]],"land":[[540000,440000,0,20000,-20000,0,0,-20000]]});
