// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-20,-10,{"coast":[[-400000,-180394,8000,373,82,21],[-383278,-180000,800,-207,2478,-188],[-380000,-180581,-89,0,89,-36]],"land":[[-400000,-180000,0,-394,8000,373,82,21,8640,0,800,-207,2478,-188,0,-186,-89,0,89,-36,0,617]]});
