// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(1,-9,3,{"coast":[[-1345392,482455,218,-79,-218,79],[-1345495,482765,271,-87,-271,87],[-1345137,482544,0,16,0,-16]]});
