// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,25,23,{"border":[[504793,480000,1768,-20000]],"county":[[500000,470001,5677,-1],[515554,460000,-10652,18755]],"land":[[520000,460000,0,20000,-20000,0,0,-20000]]});
