// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,37,23,{"coast":[[740000,478072,125,274,136,723,298,590,44,341]],"land":[[740000,460000,0,18072,125,274,136,723,298,590,44,341,-603,0]]});
