// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,16,18,{"county":[[340000,360835,-8760,1375,-1138,390,-1244,642,-3150,2175,-1405,772,-2432,868],[321871,367057,-1871,-328],[320000,377515,257,452,-257,163]],"land":[[340000,360000,0,20000,-20000,0,0,-20000]]});
