// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,29,15,{"coast":[[590464,301447,0,62,397,228,225,97,267,16,-139,-211,70,-266,-478,-63,-137,105,-205,32],[597527,300000,-6,41,31,380,-167,263,2452,-71,163,33]],"land":[[590464,301447,205,-32,137,-105,478,63,-70,266,139,211,-267,-16,-225,-97,-397,-228],[600000,300000,0,646,-163,-33,-2452,71,167,-263,-31,-380,6,-41]]});
