// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,24,{"border":[[820000,480516,1288,54,325,-44,296,-115,732,-411]],"county":[[820000,486914,387,-368,-387,-5600],[826740,500000,53,-102,-3,-294,-664,-792,25,-526,289,-853,3,-243,333,-835,440,-509,1301,-1973,-119,-323,-906,-302],[827492,493248,-7492,555]],"land":[[840000,480000,0,20000,-20000,0,0,-20000]]});
