// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,14,8,{"coast":[[298672,165348,0,69,350,-30,59,98,-136,0,0,69,689,-206,0,-74,-324,-125,-638,199]],"land":[[298672,165348,638,-199,324,125,0,74,-689,206,0,-69,136,0,-59,-98,-350,30]]});
