// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,17,22,{"county":[[340823,460000,-466,-642,-357,-271],[340000,444639,5851,-4639]],"land":[[360000,440000,0,20000,-20000,0,0,-20000]]});
