// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-62,36,{"coast":[[-1230083,739529,54,-62,622,278,0,62,-379,-47,-297,-231]],"land":[[-1230083,739529,54,-62,622,278,0,62,-379,-47]]});
