// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,9,17,{"coast":[[189720,349664,50,44,-50,-44],[191253,348621,103,-146,89,56,-43,136,-149,-46]],"land":[[191253,348621,103,-146,89,56,-43,136]]});
