// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-24,33,{"coast":[[-460000,671953,-21,-17,-109,-267,118,-24,12,15]],"land":[[-460000,660000,0,20000,0,-8047,-21,-17,-109,-267,118,-24,12,15]]});
