// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-19,-6,{"coast":[[-360000,-119558,-828,-101,68,68,-454,82,242,191,-2484,-600,-99,-82]],"land":[[-360000,-120000,0,442,-828,-101,68,68,-454,82,242,191,-2484,-600,-99,-82]]});
