// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,32,21,{"border":[[640000,430053,20000,3]],"land":[[660000,420000,0,20000,-20000,0,0,-20000]],"rivers":[[655985,440000,55,-276,952,-460,152,-189,-92,-337,-262,-468,144,-321,229,-213,928,-593,367,9,601,-326,667,-635,148,-154,62,-169,-317,-405,181,-277,200,-153]]});
