// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,10,-8,{"coast":[[205968,-160000,-1495,94,612,218,2878,544,715,282,-249,447,-1378,572,-3264,379,-1034,-57,-2753,172]],"land":[[200000,-160000,5968,0,-1495,94,612,218,2878,544,715,282,-249,447,-1378,572,-3264,379,-1034,-57,-2753,172]]});
