// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,4,14,{"coast":[[97983,280096,326,444,501,-66,919,183,149,-149,-170,-432,-99,-76],[98103,280000,-120,96]],"land":[[97983,280096,120,-96,1506,0,99,76,170,432,-149,149,-919,-183,-501,66]]});
