// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,19,{"county":[[820000,385198,171,150,450,564,3409,1262,400,388,220,692,198,11746]],"land":[[840000,380000,0,20000,-20000,0,0,-20000]]});
