// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-40,23,{"coast":[[-797986,466575,0,116,167,64,413,-38,134,-55,70,-183,-553,-28,-231,124]],"land":[[-797986,466575,231,-124,553,28,-70,183,-134,55,-413,38,-167,-64]]});
