// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,27,20,{"county":[[541724,400000,86,20000]],"land":[[560000,400000,0,20000,-20000,0,0,-20000]]});
