// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-15,32,{"land":[[-280000,640000,0,20000,-20000,0,0,-20000]],"rivers":[[-300000,654421,353,232,336,107,213,-12,1177,-393,796,46,650,-44,2170,-688,1449,-174,1880,-484,382,-45,2798,153,712,156,647,321,2387,1867,632,328,1958,641,1209,590,251,202]]});
