// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-17,22,{"coast":[[-338770,460000,-61,-122,-355,-151,-568,-58,-176,146,-70,17]],"land":[[-340000,460000,0,-168,70,-17,176,-146,568,58,355,151,61,122]]});
