// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,7,12,{"coast":[[478315,720000,18,58,219,2255,-52,346,615,692,278,1009,470,1147,137,307],[480000,740222,-76,158,39,558,37,65]],"land":[[480000,720000,0,21003,-37,-65,-39,-558,76,-158,0,-14408,-137,-307,-470,-1147,-278,-1009,-615,-692,52,-346,-219,-2255,-18,-58]]});
