// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,15,20,{"border":[[300000,400050,1784,-1],[301784,400049,3056,1911,15160,9912],[301704,400000,80,49]],"land":[[320000,400000,0,20000,-20000,0,0,-20000]]});
