// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,22,23,{"county":[[460000,479601,-450,130,-427,269]],"land":[[460000,460000,0,20000,-20000,0,0,-20000]]});
