// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(1,1,4,{"coast":[[205823,729392,267,405,962,-342,-819,-676,-410,613]],"land":[[205823,729392,410,-613,819,676,-962,342]]});
