// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,20,{"county":[[824848,400000,28,1663,87,446,383,545,3539,2325,2527,2320,400,475,420,639,421,877,243,711,150,1217,-55,2232,-866,6550]],"land":[[840000,400000,0,20000,-20000,0,0,-20000]]});
