// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,45,35,{"coast":[[903799,708649,2,42,27,-152,-29,110]],"land":[[903799,708649,29,-110,-27,152]]});
