// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-5,-2,{"county":[[-90000,-20000,0,-5500],[-90000,-25500,0,-14500],[-90000,-25500,-10000,0]],"land":[[-100000,-20000,0,-20000,20000,0,0,20000]]});
