// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,43,21,{"border":[[875004,420000,381,452,200,162,246,75,4169,513]],"land":[[880000,420000,0,20000,-20000,0,0,-20000]]});
