// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,51,-7,{"coast":[[1024603,-120000,179,-41,1099,-93,4008,134]],"land":[[1024603,-120000,179,-41,1099,-93,4008,134]]});
