// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-11,-3,{"coast":[[-200275,-54863,107,478,168,236],[-200000,-54867,-198,-29,-77,33]],"land":[[-200275,-54863,77,-33,198,29,0,718,-168,-236]]});
