// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,1,34,{"coast":[[25372,688784,259,-285,447,-157,56,70,-20,116,-111,92,-418,188,-213,-24]],"land":[[25372,688784,259,-285,447,-157,56,70,-20,116,-111,92,-418,188]]});
