// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,37,20,{"county":[[742395,418389,-327,-54,-467,-326,-782,-853,-819,-682],[744867,419319,-229,-95,-109,-165,-34,-410,-154,-360,-187,-97,-300,-8],[743854,418184,-1459,205],[749476,420000,58,-777,-108,-371,-118,-178,-181,-138,-430,-71],[748697,418465,-934,107,-2135,616,-761,131]],"land":[[760000,400000,0,20000,-20000,0,0,-20000]]});
