// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,51,9,{"county":[[1022757,190423,-279,-994,-1009,-60],[1021469,189369,-1469,61],[1022757,190423,17243,189],[1022757,190423,135,968,1073,602,396,1023,-769,899,-645,2374,-25,1176,922,559,1319,576,772,683,13,717]],"land":[[1040000,180000,0,20000,-20000,0,0,-20000]]});
