// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,12,30,{"coast":[[259703,600000,39,11,-62,75,320,188]],"land":[[260000,600000,0,274,-320,-188,62,-75,-39,-11]]});
