// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,47,18,{"county":[[940000,367891,119,-138,310,-905,-355,-507,-74,-49],[940000,364852,596,-178,2326,-1191,745,-592,17,-370,-104,-388,-294,-539,-13,-820,-144,-665,24,-109]],"land":[[960000,360000,0,20000,-20000,0,0,-20000]]});
