// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,29,23,{"border":[[589834,480000,-17,-20000]],"land":[[600000,460000,0,20000,-20000,0,0,-20000]]});
