// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-5,-7,{"county":[[-100000,-131549,10000,1549,0,10000]],"land":[[-100000,-120000,0,-20000,20000,0,0,20000]]});
