// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,19,17,{"county":[[389628,340000,-1603,10102,-810,1265,-1219,955,-1200,1310,-820,2719,-531,583,-3445,1759],[380000,358862,1634,1138]],"land":[[400000,340000,0,20000,-20000,0,0,-20000]]});
