// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-13,10,{"coast":[[-251302,210395,563,180,761,46,1263,-42,780,-225,863,-498,-499,483,-511,259,-502,166,-494,74,-1110,24,-982,-291,-132,-176]],"land":[[-251302,210395,563,180,761,46,1263,-42,780,-225,863,-498,-499,483,-511,259,-502,166,-494,74,-1110,24,-982,-291]]});
