// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,24,23,{"county":[[480000,470005,1,0,19999,-4]],"land":[[500000,460000,0,20000,-20000,0,0,-20000]]});
