// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-21,-10,{"coast":[[-420000,-180142,7634,-208,1011,-187,7042,136,465,84,828,2,108,20,7,62,1035,2,1301,-190,569,27]],"land":[[-420000,-180000,0,-142,7634,-208,1011,-187,7042,136,465,84,828,2,108,20,7,62,1035,2,1301,-190,569,27,0,394]]});
