// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,3,12,{"coast":[[69270,259470,15,-146,167,-301,205,-73,205,73,67,-69,649,516,63,170,-113,118,-190,69,-377,14,-413,-97,-278,-274]],"land":[[69270,259470,15,-146,167,-301,205,-73,205,73,67,-69,649,516,63,170,-113,118,-190,69,-377,14,-413,-97]]});
