// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-29,31,{"coast":[[-568253,636173,76,146,68,-91,-37,-75,-107,20],[-568220,636055,45,-3,-45,3],[-570116,633414,49,90,69,-16,-63,-132,-55,58]],"land":[[-568253,636173,107,-20,37,75,-68,91],[-570116,633414,55,-58,63,132,-69,16]]});
