// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,13,21,{"county":[[260000,423292,5114,-3292],[276184,440000,3816,-8026]],"land":[[280000,420000,0,20000,-20000,0,0,-20000]]});
