// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,12,18,{"border":[[240459,380000,323,-98,927,0,723,-98,1035,195,6,1],[254484,380000,653,-499,742,-381,601,-97,1445,-20,2066,98,9,-2]],"coast":[[240000,362187,2374,-1089,1888,-1002,116,-96]],"land":[[260000,360000,0,20000,-20000,0,0,-17813,2374,-1089,1888,-1002,116,-96]]});
