// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,0,10,{"coast":[[55736,641415,30,-131,154,-132,265,-65,253,85,109,162,-37,140,-204,190,-409,-13,-161,-236]],"land":[[55736,641415,30,-131,154,-132,265,-65,253,85,109,162,-37,140,-204,190,-409,-13]]});
