// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-20,13,{"coast":[[-399557,260000,-85,311,11,67,-89,218,85,92,431,21,134,-29,231,-104,134,-11,60,31,138,-141,570,-396,49,-59]],"land":[[-397888,260000,-49,59,-570,396,-138,141,-60,-31,-134,11,-231,104,-134,29,-431,-21,-85,-92,89,-218,-11,-67,85,-311]]});
