// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,45,36,{"coast":[[912471,721926,117,-524,106,-204,180,-98,-149,436,-254,390]],"land":[[912471,721926,117,-524,106,-204,180,-98,-149,436]]});
