// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-35,-8,{"coast":[[-700000,-140496,466,-43,2078,149,372,79,299,200,-248,111],[-680000,-142422,-1209,-485,-1695,-189,-820,87,-2846,-404,-646,-220,-12784,565]],"land":[[-700000,-143068,12784,-565,646,220,2846,404,820,-87,1695,189,1209,485,0,2422,-17033,0,248,-111,-299,-200,-372,-79,-2078,-149,-466,43]]});
