// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,13,19,{"border":[[260000,390050,2928,0,195,-50,69,-131,-12,-9869],[268029,380000,11971,7040]],"land":[[280000,380000,0,20000,-20000,0,0,-20000]]});
