// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,13,24,{"border":[[260000,495045,20000,7]],"county":[[266891,480000,-4395,4683,-1434,1400,248,701,-1310,1712],[260000,490792,305,638,101,3179,-406,404],[260000,496241,100,79,1410,751,449,479,81,241,80,779,470,1170,377,260]],"land":[[280000,480000,0,20000,-20000,0,0,-20000]]});
