// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,45,12,{"county":[[920000,244196,-896,-826,-1323,-2676,-716,-694],[920000,249846,-144,93,5,235,139,250],[920000,254146,-92,31,-137,156,-2234,5667]],"land":[[920000,240000,0,20000,-20000,0,0,-20000]]});
