// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,37,{"coast":[[825073,746982,0,149,85,-130,-29,-57,-56,38]],"land":[[825073,746982,56,-38,29,57,-85,130]]});
