// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,3,12,{"coast":[[205823,729392,113,347,154,58,407,-50,555,-292,-615,-608,-137,46,-67,-114,-139,114,-271,499]],"land":[[205823,729392,271,-499,139,-114,67,114,137,-46,615,608,-555,292,-407,50,-154,-58]]});
