// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,21,33,{"coast":[[439142,660000,85,37,-150,49,-109,-86],[438854,660000,812,1044,170,440,106,720,58,9],[440000,661618,-28,-66,28,29],[440000,662648,-164,-339,164,422]],"land":[[440000,660000,0,2731,-164,-422,164,339,0,-1067,-28,-29,28,66,0,595,-58,-9,-106,-720,-170,-440,-812,-1044,114,0,109,86,150,-49,-85,-37]]});
