// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-66,20,{"coast":[[-1311656,412709,25,18,-25,-18],[-1311671,412652,21,15,-21,-15],[-1311720,413566,23,1,-23,-1],[-1312107,412123,32,9,-32,-9],[-1312238,411388,23,-2,-23,2],[-1312894,411321,95,-36,-95,36]]});
