// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,38,21,{"county":[[774977,420770,-798,-214,-406,-272,-237,-284],[780000,424071,-67,-111,-74,-500,56,-1017,85,-277],[780000,421524,-79,-120,-274,-206,-488,-201,-452,-87,-2180,-167],[776527,420743,-1550,27],[761251,420000,-379,352,-872,635]],"land":[[780000,420000,0,20000,-20000,0,0,-20000]]});
