// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,44,16,{"county":[[898433,320000,-286,293,-1057,506,-10583,3072],[886507,323871,-3167,-612],[883340,323259,-729,21,-965,317,-1042,636,-604,289],[900000,339745,-1679,255],[885255,340000,-1206,-2615,-1284,-1336,-1513,-1188,-1252,-411]],"land":[[900000,320000,0,20000,-20000,0,0,-20000]]});
