// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,10,-9,{"coast":[[200000,-168144,10795,22,8637,967,568,-31],[220000,-161111,-1418,233,-622,-44,-847,289,-337,203,-197,206,-125,25,-3300,191,-3944,-195,-3242,203]],"land":[[200000,-160000,0,-8144,10795,22,8637,967,568,-31,0,6075,-1418,233,-622,-44,-847,289,-337,203,-197,206,-125,25,-3300,191,-3944,-195,-3242,203]]});
