// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,47,8,{"county":[[960000,176560,-2353,2441],[957647,179001,-2269,-121],[955378,178880,-972,657,-110,463]],"land":[[960000,160000,0,20000,-20000,0,0,-20000]]});
