// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,47,0,{"land":[[960000,0,0,20000,-20000,0,0,-20000]],"rivers":[[957048,159,-66,-159],[945632,3518,-686,-158,-1238,-81,-1684,216,-876,11,-479,140,-669,63],[947847,8902,-666,498,-137,222,-527,249,-1217,-139,-361,-193,-802,-111,-194,83,-83,166,-554,138,-388,-90,-608,139,-581,228,-664,-111,-638,0,-427,245]]});
