// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,44,15,{"county":[[900000,316559,-137,141,-454,1674,-327,744,-383,609,-266,273],[900000,306230,-20000,496]],"land":[[900000,300000,0,20000,-20000,0,0,-20000]]});
