// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-60,34,{"coast":[[-1200000,690450,377,-128,220,-2,-183,392,52,236,-114,2,-127,-163,-210,-87,-15,-14]],"land":[[-1200000,690686,0,-236,377,-128,220,-2,-183,392,52,236,-114,2,-127,-163,-210,-87]]});
