// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,1,-3,{"county":[[20000,-60000,25,0],[30038,-60000,9962,1],[20025,-60000,10013,0]],"land":[[20000,-40000,0,-20000,20000,0,0,20000]]});
