// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,-21,11,{"coast":[[-1209335,706091,342,77,197,-73,198,156,-466,102,-161,-53,-110,-209],[-1200184,690512,184,-62],[-1200000,690662,-184,-150]],"land":[[-1209335,706091,342,77,197,-73,198,156,-466,102,-161,-53],[-1200000,690662,-184,-150,184,-62]]});
