// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,24,24,{"border":[[488250,500000,89,-196,5351,-7300,6310,-6562]],"land":[[500000,480000,0,20000,-20000,0,0,-20000]]});
