// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,29,-6,{"coast":[[599434,-114451,39,-151,205,-180,256,-152,66,-20],[600000,-114382,-207,17,-359,-86]],"land":[[599434,-114451,39,-151,205,-180,256,-152,66,-20,0,572,-207,17]]});
