// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,16,{"coast":[[520000,338339,1603,473,1703,323,353,-1,527,244,482,322,1177,300]],"land":[[540000,320000,0,20000,-20000,0,0,-1661,1603,473,1703,323,353,-1,527,244,482,322,1177,300,14155,0]]});
