// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,47,2,{"land":[[960000,40000,0,20000,-20000,0,0,-20000]],"rivers":[[941231,50366,-674,350,-557,16]]});
