// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-4,-1,{"coast":[[-60000,-879,-160,-14,-411,-105,-252,-319,-160,18,-245,129,-43,261,61,106,434,126,440,397,269,134,-68,137,18,9]],"land":[[-80000,0,0,-20000,20000,0,0,19121,-160,-14,-411,-105,-252,-319,-160,18,-245,129,-43,261,61,106,434,126,440,397,269,134,-68,137,18,9]]});
