// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-38,23,{"coast":[[-760000,461321,438,242,154,220,-51,217,265,193,82,360,-131,173,-369,4,-183,102,-205,-182]],"land":[[-760000,461321,438,242,154,220,-51,217,265,193,82,360,-131,173,-369,4,-183,102,-205,-182]]});
