// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,16,23,{"county":[[340000,471442,-6302,2923,-767,490,975,3892,-117,484,126,412,3824,357]],"land":[[340000,460000,0,20000,-20000,0,0,-20000]],"rivers":[[333398,480000,271,-101,921,-149,429,100,549,-26,546,83,545,-123,335,35,508,-101,988,-393,517,30,146,90,338,481,134,74]]});
