// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-1,-4,{"county":[[-9993,-60000,5002,0],[-20000,-60000,10007,0],[-4991,-60000,4991,0]],"land":[[-20000,-60000,0,-20000,20000,0,0,20000]]});
