// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,32,-8,{"coast":[[650696,-140080,70,80],[653255,-140000,-162,-80,-2397,0]],"land":[[650766,-140000,-70,-80,2397,0,162,80]]});
