// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,27,17,{"coast":[[540000,347264,568,74,892,15,938,-93,988,-248,804,-344,1115,-636,859,-246,1325,-895,1654,-1720,679,-957,543,-405,634,-1159,275,-650]],"land":[[560000,340000,0,20000,-20000,0,0,-12736,568,74,892,15,938,-93,988,-248,804,-344,1115,-636,859,-246,1325,-895,1654,-1720,679,-957,543,-405,634,-1159,275,-650]]});
