// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(1,-8,4,{"coast":[[-1209335,706091,737,160,-466,102,-271,-262],[-1200184,690512,781,-192,-131,628,-650,-436],[-1250300,653762,211,-37,-211,37],[-1230083,739529,676,278,-676,-278]],"land":[[-1209335,706091,737,160,-466,102],[-1200184,690512,781,-192,-131,628]]});
