// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,9,15,{"coast":[[186017,319534,0,68,200,78,140,-24,386,-314,503,56,-106,-73,-38,-119,7,-293,-68,74,-212,-95,-242,49,-204,156,-182,390,-184,47]],"land":[[186017,319534,184,-47,182,-390,204,-156,242,-49,212,95,68,-74,-7,293,38,119,106,73,-503,-56,-386,314,-140,24,-200,-78]]});
