// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,8,21,{"border":[[179863,435800,137,-24],[179459,440000,67,-274,425,-1145,49,-246]],"coast":[[179863,435800,9,-252,128,-452],[179221,440000,100,-309,527,-3489,15,-402],[180000,439828,-84,38,-75,-178,159,-202]],"land":[[180000,440000,0,-514,-159,202,75,178,84,-38,0,172,-779,0,100,-309,527,-3489,15,-402,9,-252,128,-452]]});
