// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,-3,3,{"coast":[[-180000,182455,214,-44,175,-239,198,-85,111,-358,-39,-200,244,-657,275,-383,-163,-159,161,-110,-127,-176,23,-44]],"land":[[-180000,180000,1072,0,-23,44,127,176,-161,110,163,159,-275,383,-244,657,39,200,-111,358,-198,85,-175,239,-214,44]]});
