// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,50,8,{"county":[[1011327,160000,-1706,154,-1340,469,-933,758,-2106,291],[1005242,161672,-4528,-440],[1000714,161232,-714,78]],"land":[[1020000,160000,0,20000,-20000,0,0,-20000]]});
