// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-24,30,{"coast":[[-466163,610362,100,36,260,-158,-20,-155,-191,32,-149,245]],"land":[[-466163,610362,149,-245,191,-32,20,155,-260,158]]});
