// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,40,22,{"county":[[802726,457431,17274,-1764],[800000,457230,143,33,2583,168]],"land":[[820000,440000,0,20000,-20000,0,0,-20000]]});
