// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-38,27,{"coast":[[-742342,546921,156,263,82,-71,-16,-140,-139,-83,-83,31]],"land":[[-742342,546921,83,-31,139,83,16,140,-82,71]]});
