// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,20,13,{"coast":[[412551,280000,118,-178,718,-515,771,-237,466,-9,403,109,415,242,28,176,258,134,76,278]],"land":[[420000,260000,0,20000,-7449,0,118,-178,718,-515,771,-237,466,-9,403,109,415,242,28,176,258,134,76,278,4196,0]]});
