// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,29,18,{"border":[[599812,380000,0,-20000]],"county":[[599812,373335,188,0],[580604,360000,17,8607,19191,426],[580000,379859,919,-6,18893,-345]],"land":[[600000,360000,0,20000,-20000,0,0,-20000]]});
