// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,31,25,{"county":[[621823,520000,1139,-1407,649,-1094,138,-1135,1278,-1492,167,-571,32,-369,-111,-381,-694,-1160,419,-2404,-1491,-4124,-1072,-3327,-429,-811,-392,-261,-151,-225,-149,-1239]],"land":[[640000,500000,0,20000,-20000,0,0,-20000]]});
