// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,32,23,{"land":[[660000,460000,0,20000,-20000,0,0,-20000]],"rivers":[[660000,469535,-159,0,-226,-73,-355,-541,-329,-225,-856,-140,-384,-249,-689,-1583,142,-779,-117,-621,-203,-295,-584,-496,-371,-468,-102,-221,-175,-936,-235,-429,-203,-712,-238,-185,-62,-187,-186,-1108,77,-287]]});
