// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,48,2,{"county":[[978585,40000,-805,828,-204,400,21,178,743,1102,472,1092,1188,1022]],"land":[[980000,40000,0,20000,-20000,0,0,-20000]]});
