// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-28,1,{"coast":[[-557511,20000,-26,2,-34,40,91,88,247,139,-289,81,-325,-6,125,124,-116,81,-419,68,-1743,-111],[-560000,23380,68,32,92,-52,-160,-49]],"land":[[-560000,40000,0,-20000,2489,0,-26,2,-34,40,91,88,247,139,-289,81,-325,-6,125,124,-116,81,-419,68,-1743,-111],[-560000,23311,160,49,-92,52,-68,-32]]});
