// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,33,-8,{"coast":[[664771,-151039,192,-118,14433,-905,560,-127,44,-1],[680000,-151651,-1689,319,-12200,605,-1340,-312]],"land":[[664771,-151039,192,-118,14433,-905,560,-127,44,-1,0,539,-1689,319,-12200,605]]});
