// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,19,{"border":[[1050000,400000,0,-15870,-1844,67,-433,-148,-721,-579,-408,-247,-1552,-575,-314,-314,-77,-412,337,-1922]],"coast":[[1050000,400000,0,-20000]],"land":[[1050000,380000,0,20000,-10000,0,0,-20000]]});
