// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,30,25,{"county":[[600878,519503,-878,-32],[602448,519357,-1570,146],[604169,520000,-226,-203,-611,-314,-884,-126],[602543,520000,-95,-643]],"land":[[620000,500000,0,20000,-20000,0,0,-20000]]});
