// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,17,23,{"county":[[341148,460447,9504,2475,2970,3564,2079,2178,4299,3425],[341148,460447,-325,-447],[341148,460447,-495,10692,-653,303]],"land":[[360000,460000,0,20000,-20000,0,0,-20000]],"rivers":[[340227,480000,409,-106,199,106],[341563,480000,248,-123,159,-16,183,139]]});
