// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,35,23,{"border":[[719970,480000,-36,-187,-198,-265,-1,-173,66,-75,199,-25]],"county":[[706653,480000,-90,-1774],[706563,478226,-4931,-3182,-369,-347,-1145,-1673,-118,-214],[706563,478226,3545,1774],[711941,480000,7793,-621]],"land":[[720000,460000,0,20000,-20000,0,0,-20000]]});
