// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,18,24,{"border":[[360000,499850,2709,-2449,269,-158,337,-79,16685,-555]],"land":[[380000,480000,0,20000,-20000,0,0,-20000]]});
