// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,30,21,{"border":[[600000,430047,20000,3]],"land":[[620000,420000,0,20000,-20000,0,0,-20000]]});
