// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,35,{"land":[[540000,700000,0,20000,-20000,0,0,-20000]],"rivers":[[540000,703837,-386,-23,-171,-83,-90,-192,4,-227,169,-659,-22,-749,-302,-405,70,-206,-75,-196,-150,-148,-325,-140,-575,-575,-72,-175,-177,6,-3,-65]]});
