// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,21,28,{"land":[[440000,560000,0,20000,-20000,0,0,-20000]],"rivers":[[440000,571229,-105,26,-406,419,-310,210,-1186,126,-1592,632,-1196,-38,-284,-76,-365,-213,-570,-119,-824,-507,-228,-245,-930,-210,-808,-376,-843,-143,-670,-359,-345,-93,-706,-83,-820,-240,-644,-71,-635,-158,-1582,125,-1758,-153,-335,36,-2018,679,-840,577]]});
