// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-12,4,{"coast":[[-240000,98763,51,42,310,-206,96,90,-201,525,-256,290],[-240000,99823,122,-18,127,195]],"land":[[-240000,100000,0,-1237,51,42,310,-206,96,90,-201,525,-256,290,0,319,122,-18,127,195]]});
