// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,9,{"county":[[1040000,190612,1708,19],[1046708,200000,-1546,-3888,-2192,-4038,-1262,-1443]],"land":[[1040000,200000,0,-20000,10000,0,0,20000]]});
