// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,9,7,{"border":[[599812,430046,0,-10046],[589813,455039,0,-4993,9867,4,125,-71,7,-19933],[540000,430441,49813,24598],[589834,480000,-21,-24961],[599812,430046,188,1]],"land":[[600000,420000,0,60000,-60000,0,0,-60000]]});
