// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-62,22,{"coast":[[-1220611,441094,9,-113,38,-86,209,-119,138,-36,217,-18],[-1220000,441618,-112,-158,-385,-162,-114,-204]],"land":[[-1220611,441094,9,-113,38,-86,209,-119,138,-36,217,-18,0,896,-112,-158,-385,-162]]});
