// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-10,-5,{"coast":[[-197874,-80000,-556,-134,-303,-12,-1010,146]],"land":[[-200000,-80000,0,-20000,20000,0,0,20000,-17874,0,-556,-134,-303,-12,-1010,146]]});
