// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,17,19,{"county":[[360000,386255,-169,109,-1187,447,-288,287,-102,214,133,277,851,724,762,960]],"land":[[360000,380000,0,20000,-20000,0,0,-20000]]});
