// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,25,20,{"border":[[500000,419952,9646,-4374,205,-25,9006,4447]],"land":[[520000,400000,0,20000,-20000,0,0,-20000]]});
