// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,29,26,{"county":[[595143,520000,-4239,4127,-587,747,-186,387,-447,4008,-2023,6619,-4688,3033,-747,1079]],"land":[[600000,520000,0,20000,-20000,0,0,-20000]]});
