// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,45,22,{"border":[[900000,449395,3122,-9395]],"county":[[904065,440000,11707,18344,4228,1073]],"land":[[920000,440000,0,20000,-20000,0,0,-20000]]});
