// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,28,31,{"land":[[580000,620000,0,20000,-20000,0,0,-20000]],"rivers":[[580000,631286,-466,-333,-1114,-100,-232,-59,-496,-274,-343,-20,-203,-89,-891,-848,-244,-385,-863,-634,-171,-60,-329,9,-1814,-311,-490,104,-430,-120,-986,-40,-4961,393,-789,313,-1734,253,-1033,579,-343,278,-1063,103,-1005,-64]]});
