// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,13,22,{"county":[[270123,452746,-10123,46],[270123,452746,6061,-12746],[270123,452746,-3451,7254]],"land":[[280000,440000,0,20000,-20000,0,0,-20000]]});
