// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-13,24,{"coast":[[-260000,486504,108,32,-108,60]],"land":[[-260000,486504,108,32,-108,60]]});
