// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-5,37,{"coast":[[-100000,750000,20000,0]],"land":[[-80000,740000,0,10000,-20000,0,0,-10000]],"rivers":[[-83529,741950,622,793,357,324,427,-4,448,-517,157,-91,997,-473,521,-177]]});
