// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,39,30,{"border":[[780000,604501,1193,-978,4092,-1939,3167,-728,1238,-396,9436,546,289,-121,585,-638]],"land":[[800000,600000,0,20000,-20000,0,0,-20000]],"rivers":[[799750,600000,80,224,170,90]]});
