// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,4,{"coast":[[533447,80000,0,29,137,74,-369,206,-100,210,-1076,329,-342,32,-310,-100,652,-643,-14,-137]],"land":[[533447,80000,0,29,137,74,-369,206,-100,210,-1076,329,-342,32,-310,-100,652,-643,-14,-137]]});
