// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-45,-6,{"coast":[[-880407,-110883,407,-135],[-880000,-111196,-65,-34,65,-12],[-880000,-110914,-407,31]],"land":[[-880000,-110914,-407,31,407,-135,0,-178,-65,-34,65,-12]]});
