// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,17,21,{"border":[[340000,424949,20000,13076]],"land":[[360000,420000,0,20000,-20000,0,0,-20000]]});
