// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,29,22,{"border":[[589813,455039,0,-4993,9867,4,125,-71,4,-9979],[580000,450193,9813,4846],[589817,460000,-4,-4961]],"land":[[600000,440000,0,20000,-20000,0,0,-20000]]});
