// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-52,37,{"coast":[[-1040000,748069,443,31,636,-93,228,-91,553,-521,-226,16,-301,144,-760,-131,-186,-86,-232,-343,-155,-26]],"land":[[-1040000,746969,155,26,232,343,186,86,760,131,301,-144,226,-16,-553,521,-228,91,-636,93,-443,-31]]});
