// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,11,20,{"border":[[220000,405399,98,-97,3604,-2100,1298,-898,699,-606,302,-498,401,-898,107,-302],[220000,419723,3806,-2431,610,-195,1685,-222,360,-100,2193,-968,1019,-257,134,-160,24,-15390]],"land":[[240000,400000,0,20000,-20000,0,0,-20000]]});
