// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,17,17,{"county":[[357174,340000,-3183,2913],[350109,340000,3882,2913],[353991,342913,-5983,9637,-6265,7368,-127,82]],"land":[[360000,340000,0,20000,-20000,0,0,-20000]]});
