// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,14,24,{"border":[[280000,495052,14890,6,1577,-8178,-116,-229,-2410,-1610,-174,-319,-519,-4722]],"land":[[300000,480000,0,20000,-20000,0,0,-20000]]});
