// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,-3,9,{"coast":[[-180000,595457,54,-33,295,137,686,382,674,638,459,250,303,495,2268,1967,-6,171,217,0,253,140,466,396]],"land":[[-180000,600000,0,-4543,54,-33,295,137,686,382,674,638,459,250,303,495,2268,1967,-6,171,217,0,253,140,466,396]]});
