// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,6,{"land":[[1040000,140000,0,-20000,10000,0,0,20000]],"rivers":[[1049771,136497,-220,-161,-181,-266,-1011,-465,-236,-240,-183,-92,-147,-230,-218,-77,-241,-186,-743,-82,-345,-194,-758,-171,-1071,-117,-402,-120,-977,-568,-706,-211,-349,-39,-79,-181,-583,-294,-603,-3,-718,-208]]});
