// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-64,20,{"coast":[[-1269295,419374,37,84,102,-41,-8,-26,-131,-17]],"land":[[-1269295,419374,131,17,8,26,-102,41]]});
