// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,23,{"border":[[822641,480000,1635,-918,304,-391,1141,-3014,169,-310,5729,-6856,8381,-4131]],"county":[[824286,479069,2476,-19069]],"land":[[840000,460000,0,20000,-20000,0,0,-20000]]});
