// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,32,29,{"land":[[660000,580000,0,20000,-20000,0,0,-20000]],"rivers":[[660000,580557,-294,-160,-479,-397]]});
