// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,14,17,{"border":[[280000,354882,418,26,1747,629,839,-699,1397,-140,1468,-349,1398,-140,2725,0,2446,-350,350,909,839,279,978,-279,1048,-1188,909,-1258,699,-1188,978,-909,1048,-629,713,-509]],"land":[[300000,340000,0,20000,-20000,0,0,-20000]]});
