// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-27,29,{"coast":[[-521177,594849,131,-223,400,-204,-9,232,-130,139,-392,56]],"land":[[-521177,594849,131,-223,400,-204,-9,232,-130,139]]});
