// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,25,24,{"border":[[500000,485942,4524,-4704,196,-405,73,-833]],"county":[[504685,480951,12029,5630],[516714,486581,3286,1541],[511865,500000,3026,-10374,1823,-3045]],"land":[[520000,480000,0,20000,-20000,0,0,-20000]]});
