// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,47,17,{"border":[[958444,351418,1556,-1606],[958444,351418,1556,1616],[958444,351418,1556,441]],"land":[[960000,340000,0,20000,-20000,0,0,-20000]]});
