// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,22,25,{"border":[[447941,520000,252,-292,335,-312,192,-122,198,-36,126,-181,80,-349,177,-168,1897,-1041,417,-171,5135,-1079,963,-76,1817,208,470,-2]],"land":[[460000,500000,0,20000,-20000,0,0,-20000]]});
