// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-67,0,{"coast":[[-1330971,343,24,-27,166,-39,33,-83,217,-18,59,60,-14,160,-340,-3,-145,-50]],"land":[[-1330971,343,24,-27,166,-39,33,-83,217,-18,59,60,-14,160,-340,-3]]});
