// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,44,21,{"border":[[880000,421202,20000,2459]],"land":[[900000,420000,0,20000,-20000,0,0,-20000]]});
