// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,31,17,{"coast":[[636832,340000,495,159,551,244,242,29,169,416,68,44,1643,715]],"land":[[640000,340000,0,20000,-20000,0,0,-20000,16832,0,495,159,551,244,242,29,169,416,68,44,1643,715]]});
