// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,27,18,{"county":[[541698,379871,24,-13345,-1680,-108,-42,-13],[541698,379871,0,129],[557231,379782,2769,33],[541698,379871,15533,-89]],"land":[[560000,360000,0,20000,-20000,0,0,-20000]]});
