// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,-3,{"coast":[[1050000,-60000,0,20000]],"lakeEdge":[[1040000,-44817,88,22,2102,177,524,-106,262,-118,9,-153,-371,-312,-215,-100,-1192,-35,-1207,-283]],"lakes":[[1040000,-45725,1207,283,1192,35,215,100,371,312,-9,153,-262,118,-524,106,-2102,-177,-88,-22]],"land":[[1040000,-40000,0,-20000,10000,0,0,20000]]});
