// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,24,{"county":[[528414,500000,1515,-6164],[520000,488122,8428,3953,207,161,456,684,838,916],[534800,496161,828,-6,294,-60,1990,-600,1012,-446,430,-269,646,-536],[529929,493836,920,847,1241,745,616,257,2094,476]],"land":[[540000,480000,0,20000,-20000,0,0,-20000]]});
