// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-38,21,{"coast":[[-750883,420000,283,492,603,564,452,222,591,-20,-75,-75,12,-80,167,-75,339,-28,451,-361,26,-200,448,-284,271,-30,118,-125]],"land":[[-747197,420000,-118,125,-271,30,-448,284,-26,200,-451,361,-339,28,-167,75,-12,80,75,75,-591,20,-452,-222,-603,-564,-283,-492]]});
