// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,24,20,{"border":[[499895,420000,105,-48],[480000,417127,4823,1076,1173,607,1460,1190]],"land":[[500000,400000,0,20000,-20000,0,0,-20000]]});
