// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,21,27,{"land":[[440000,540000,0,20000,-20000,0,0,-20000]],"rivers":[[439085,549784,202,-125,208,125,344,-238,97,-163,64,-428]]});
