// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,10,23,{"county":[[200000,460013,5559,-13],[220000,461878,-2436,-1878],[220000,466783,-7337,5217,-2250,1965,-3615,5154,-1227,881]],"land":[[220000,460000,0,20000,-20000,0,0,-20000]]});
