// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,10,22,{"county":[[207782,459995,21,-4280,607,-15715],[205559,460000,2223,-5],[217564,460000,-6,-5],[217558,459995,-9776,0]],"land":[[220000,440000,0,20000,-20000,0,0,-20000]]});
