// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-14,31,{"land":[[-260000,620000,0,20000,-20000,0,0,-20000]],"rivers":[[-260000,628355,-260,342,-178,685,42,124,396,474],[-260000,631077,-190,174,-522,216,-378,310,-284,555,-76,365,-437,374,-289,426,-317,782,-329,2645,-360,570,-243,611,-23,183,130,857,-235,469,-31,386]]});
