// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-16,29,{"land":[[-300000,580000,0,20000,-20000,0,0,-20000]],"rivers":[[-304399,600000,-82,-60,-412,60],[-304994,600000,-886,-408,-256,-52,-555,-40,-626,79,-682,-149,-560,-252,-1175,168,-603,-167,-902,22,-1030,-317,-364,143,-120,236,-542,58,-470,570,-43,109]]});
