// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,28,{"border":[[820000,570034,9792,0],[820000,579477,9792,-9443],[829792,570034,6621,-10034]],"land":[[840000,560000,0,20000,-20000,0,0,-20000]]});
