// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,22,18,{"border":[[448448,360000,35,243,30,1897,-743,5184,129,582,1460,3427,-16,393,-709,2082,-168,199,-527,296,32,208,245,432,-80,192,-573,635,-350,1311,848,2668,47,251]],"land":[[460000,360000,0,20000,-20000,0,0,-20000]]});
