// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,46,23,{"coast":[[920000,461564,838,-328,1237,-336,2940,-437,2082,97,222,-98,204,-192,448,-62,186,-126,85,-82]],"land":[[928242,460000,-85,82,-186,126,-448,62,-204,192,-222,98,-2082,-97,-2940,437,-1237,336,-838,328,0,-1564]]});
