// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,20,{"border":[[1040000,407373,677,-257,990,352,395,-54,746,-251,2823,69,292,122,783,759,440,201,545,60,2029,-26,280,-56,0,-8292]],"coast":[[1050000,420000,0,-20000]],"land":[[1050000,400000,0,20000,-10000,0,0,-20000]]});
