// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,12,19,{"border":[[240000,380140,459,-140],[243473,380000,1024,97,1963,898,1035,401,621,0,664,-196,561,-283,342,-19,1323,605,825,0,825,-107,1828,-1396],[240000,390051,20000,-1]],"land":[[260000,380000,0,20000,-20000,0,0,-20000]]});
