// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,49,10,{"border":[[980000,213971,2080,-246,12187,805,349,-73,3934,-1586,360,-99,319,37,336,217,435,411]],"land":[[1000000,200000,0,20000,-20000,0,0,-20000]],"rivers":[[999456,200000,-157,163,-551,62,-1024,-205,4,-20]]});
