// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,-5,{"coast":[[1048748,-80383,166,-493,202,-270,884,-559,0,-1772,-321,-285,-86,-226,407,-125,0,3786,-890,71,-362,-127]],"land":[[1048748,-80383,166,-493,202,-270,884,-559,0,-1772,-321,-285,-86,-226,407,-125,0,3786,-890,71]]});
