// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,39,-8,{"coast":[[798574,-156174,497,-126,929,-38],[800000,-156006,-1040,-43,-386,-125]],"land":[[798574,-156174,497,-126,929,-38,0,332,-1040,-43]]});
