// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,28,33,{"land":[[580000,660000,0,20000,-20000,0,0,-20000]],"rivers":[[580000,660856,-268,-61,-567,-416,-46,-330,-89,-49],[560852,677863,-198,256,-325,118,-329,21]]});
