// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,19,25,{"border":[[390893,520000,344,-2336,21,-2394,647,-20,300,-56,280,-135,1573,-1471,468,-326,541,-209,3182,-760,320,-34,682,410,581,34,168,-29]],"land":[[400000,500000,0,20000,-20000,0,0,-20000]],"rivers":[[400000,519910,-386,12,-1258,-173,-590,-330,-276,58,-339,322,-86,201]]});
