// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,45,21,{"border":[[903122,440000,3254,-9790,-6,-229,-103,-219,-4399,-6798],[901868,422964,108,-1459,-63,-1460,5,-45],[900000,423661,1053,130,151,-25,664,-802]],"land":[[920000,420000,0,20000,-20000,0,0,-20000]]});
