// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,-20,-2,{"coast":[[-1200000,-61339,2419,638,1776,701]],"land":[[-1200000,-60000,0,-1339,2419,638,1776,701]]});
