// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-24,26,{"coast":[[-467237,524885,63,91,127,-21,183,-756,-46,-112,-259,281,-29,200,83,203,-122,114]],"land":[[-467237,524885,122,-114,-83,-203,29,-200,259,-281,46,112,-183,756,-127,21]]});
