// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,30,22,{"county":[[600002,449999,-2,-1],[620000,449999,-19998,0]],"land":[[620000,440000,0,20000,-20000,0,0,-20000]]});
