// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-18,-4,{"coast":[[-355748,-60000,-116,-346,-350,-347,-922,-346,-736,-107,-744,55,-1214,380,-170,34]],"land":[[-360000,-60000,0,-677,170,-34,1214,-380,744,-55,736,107,922,346,350,347,116,346]]});
