// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,45,16,{"county":[[920000,330572,-2384,-873,-1275,-191],[916341,329508,-677,703,-2079,999,-707,639,-5310,2388,-445,811,-128,3148,-150,695,-1695,641,-1886,220],[903264,339752,-820,-143,-1279,-41],[901165,339568,-1165,177]],"land":[[920000,320000,0,20000,-20000,0,0,-20000]]});
