// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-23,17,{"coast":[[-460000,357849,338,671,218,371,145,193,203,207,316,593,76,116]],"land":[[-460000,360000,0,-20000,0,17849,338,671,218,371,145,193,203,207,316,593,76,116]]});
