// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-2,36,{"land":[[-20000,720000,0,20000,-20000,0,0,-20000]],"rivers":[[-40000,737513,134,84,188,298,720,-73,403,-136,579,171,321,306,593,249,496,1253,118,105,196,38,167,-101,63,-235,6,-483,118,-403,257,-293,362,-101,430,176,193,273,-64,272,-402,554,306,533],[-33388,740000,181,-123,158,123]]});
