// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-60,-4,{"coast":[[-1200000,-61361,843,196,1576,464,1457,532,327,169]],"land":[[-1200000,-60000,0,-1361,843,196,1576,464,1457,532,327,169]]});
