// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,27,{"border":[[836413,560000,2978,-4512,0,-15488]],"coast":[[820000,540637,81,-27,744,-610]],"county":[[840000,554336,-609,37]],"land":[[820000,540000,0,637,81,-27,744,-610,19175,0,0,20000,-20000,0]]});
