// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-13,-8,{"county":[[-260000,-158646,2474,1061,3293,1135,1383,394,3796,753,6818,1105,2236,393]],"land":[[-260000,-140000,0,-20000,20000,0,0,20000]]});
