// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,24,21,{"border":[[499799,420043,96,-43],[487456,420000,4706,3837,155,-16,7482,-3778],[500000,421092,-201,-1049]],"land":[[500000,420000,0,20000,-20000,0,0,-20000]]});
