// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,15,18,{"county":[[320000,366729,-227,-39,-2463,-1077,-1049,-634,-1787,-803],[314474,364176,-1980,155],[312494,364331,7506,13184],[320000,378130,-2966,1870],[300000,367295,12494,-2964]],"land":[[320000,360000,0,20000,-20000,0,0,-20000]]});
