// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,5,{"land":[[1040000,120000,0,-20000,10000,0,0,20000]],"rivers":[[1040000,102829,303,-371,-303,-182],[1040000,102004,81,-109,337,-239,162,-493,402,-163,46,-203,-274,-205,32,-102,273,-209,40,-99,-41,-182]]});
