// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,28,24,{"border":[[577595,500000,893,-875,567,-251,525,-890,77,-223,127,-1163,-20,-334,-99,-312,-597,-766,-73,-288,72,-312,190,-225,743,-448]],"land":[[580000,480000,0,20000,-20000,0,0,-20000]]});
