// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,23,17,{"county":[[467872,360000,-579,-870,6,-2795,-805,-4441,-297,-2221,-76,-2042,42,-1764,-264,-1291,87,-559,522,-480,2165,-2847,441,-690]],"land":[[480000,340000,0,20000,-20000,0,0,-20000]]});
