// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-8,-7,{"county":[[-154555,-140000,14555,2255]],"land":[[-160000,-120000,0,-20000,20000,0,0,20000]]});
