// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,40,28,{"border":[[800000,563356,7664,2522,11541,3866,587,290,208,0],[819458,580000,542,-523]],"land":[[820000,560000,0,20000,-20000,0,0,-20000]]});
