// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-14,-8,{"coast":[[-280000,-158373,463,363,940,205,401,164,397,53,435,-237,-193,-74,-1104,-143,-74,-85,204,-114,-721,-228,-748,-410]],"county":[[-264091,-160000,304,89,3586,1179,201,86]],"land":[[-280000,-140000,0,-18373,463,363,940,205,401,164,397,53,435,-237,-193,-74,-1104,-143,-74,-85,204,-114,-721,-228,-748,-410,0,-1121,20000,0,0,20000]]});
