// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-61,34,{"coast":[[-1200184,690512,184,-62],[-1200000,690686,-184,-174]],"land":[[-1200000,690686,-184,-174,184,-62]]});
