// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,21,16,{"border":[[431585,320000,1244,1636,135,320,232,2438,117,330,287,266,1227,662,5173,3177]],"land":[[440000,320000,0,20000,-20000,0,0,-20000]]});
