// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,19,23,{"border":[[382804,460000,45,43,335,180,403,8,1217,-231],[392356,480000,-65,-20000]],"county":[[392451,463546,5238,61,946,270,-1388,2854,-11,246,132,544,-107,378,107,1194,-377,696,89,389,102,178,154,73,1370,170,355,1282,939,762],[392303,463546,148,0],[380000,470248,12324,0]],"land":[[400000,460000,0,20000,-20000,0,0,-20000]]});
