// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,33,22,{"county":[[671771,460000,2320,-20000]],"land":[[680000,440000,0,20000,-20000,0,0,-20000]],"rivers":[[680000,454972,-7,5,-296,411,-288,-29,-422,86,-291,194,-727,1018,-230,-73,-289,373,-242,189,-377,965,-264,238,-367,126,-946,-19,-167,69,-87,461,-246,346,-137,341,-449,307,-17,20]]});
