// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,42,24,{"coast":[[854406,500000,189,-104,945,-382,1075,-99,1898,-514,1487,-271]],"land":[[860000,480000,0,18630,-1487,271,-1898,514,-1075,99,-945,382,-189,104,-14406,0,0,-20000]]});
