// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,6,-8,{"coast":[[121352,-160000,-1352,434],[120000,-158027,654,-122,205,-95,35,-156,-120,-112,-575,-213,82,-79,2244,-511,4421,-316,289,-120,233,-249]],"land":[[120000,-140000,0,-20000,1352,0,-1352,434,0,1539,654,-122,205,-95,35,-156,-120,-112,-575,-213,82,-79,2244,-511,4421,-316,289,-120,233,-249,12532,0,0,20000]]});
