// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,51,21,{"coast":[[1039161,420000,839,335],[1040000,425642,-168,164,-156,322,-70,377,-166,312,6,232,496,912,58,50]],"land":[[1040000,420000,0,8011,-58,-50,-496,-912,-6,-232,166,-312,70,-377,156,-322,168,-164,0,-5307,-839,-335]]});
