// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,18,{"county":[[528839,360000,146,152,418,1119,418,1398,1057,935,1377,843,2738,707],[534993,365154,0,-175],[534993,364979,6,-3739,59,-1240],[540000,366405,-5007,-1426]],"land":[[540000,360000,0,20000,-20000,0,0,-20000]]});
