// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,27,29,{"border":[[542296,600000,74,-108,468,-215,893,-552,359,-429,225,-56,856,0,517,-192,368,169,1140,23,596,178,455,212,255,233,407,716,87,21]],"land":[[560000,580000,0,20000,-20000,0,0,-20000]],"rivers":[[548997,600000,-93,-23,-408,-716,-255,-232,-958,-369,-1233,-45,-367,-168,-517,192,-855,0,-227,55,-358,429,-892,552,-469,216,-75,109]]});
