// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,16,{"border":[[1040000,333471,401,-202,742,-647,1095,-1441,750,-558,60,-92,-26,-130,-316,-761,-196,-947,171,-1706,-401,-1200,49,-414,187,-379,304,-322,615,-232,177,-125,648,-866,31,-123,-144,-582,-315,-189,-69,-274,448,-349,245,-289,317,-211,99,-291,-187,-1084,32,-57]],"land":[[1050000,320000,0,20000,-10000,0,0,-20000]]});
