// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-6,-1,{"county":[[-120000,-3650,20000,0]],"land":[[-120000,0,0,-20000,20000,0,0,20000]]});
