// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,38,22,{"coast":[[760000,456868,91,92,87,300,183,94,121,469,-80,342,284,581,178,118,630,199,184,115,87,148,-241,674]],"land":[[780000,440000,0,20000,-18476,0,241,-674,-87,-148,-184,-115,-630,-199,-178,-118,-284,-581,80,-342,-121,-469,-183,-94,-87,-300,-91,-92,0,3132,0,-20000]]});
