// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,11,22,{"county":[[240000,452885,-348,1,-3877,3026,-281,2057],[235494,457969,-2273,-1167],[233221,456802,-2129,1400,-2896,1798]],"land":[[240000,440000,0,20000,-20000,0,0,-20000]]});
