// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,42,23,{"border":[[840000,464380,358,-177,930,-324,18712,-2518]],"land":[[860000,460000,0,20000,-20000,0,0,-20000]]});
