// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(1,0,2,{"coast":[[96396,479448,436,-509,2142,-905,631,142,136,375,546,376,-438,582,-958,491],[96863,480000,-2,-50,-465,-502]],"land":[[96396,479448,436,-509,2142,-905,631,142,136,375,546,376,-438,582,-958,491,-2028,0,-2,-50]]});
