// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,5,-10,{"coast":[[100000,-181497,1591,371,-1048,91,-256,114,-85,141,70,88,657,259,1377,185,142,139,13,109]],"land":[[100000,-180000,0,-1497,1591,371,-1048,91,-256,114,-85,141,70,88,657,259,1377,185,142,139,13,109]]});
