// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,50,9,{"land":[[1020000,180000,0,20000,-20000,0,0,-20000]],"rivers":[[1001302,200000,8,-29,-176,29],[1000329,200000,-329,-199]]});
