// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,39,24,{"border":[[780000,484862,363,-225,125,-172,258,-653,103,-538,129,-52,651,163,171,-31,61,-187,-176,-539,144,-208,257,-154,29,-235,-171,-186,-371,-99,-115,-91,-332,-755,-39,-170,240,-730]],"land":[[800000,480000,0,20000,-20000,0,0,-20000]]});
