// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,18,23,{"county":[[360000,472089,2037,1624],[362037,473713,5939,-1287,1782,-2178,10242,0]],"land":[[380000,460000,0,20000,-20000,0,0,-20000]]});
