// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,51,14,{"border":[[1029435,280000,183,101,584,642,347,-89,1027,-654]],"land":[[1040000,280000,0,20000,-20000,0,0,-20000]],"rivers":[[1031568,280000,-1023,651,-347,90,-584,-643,-178,-98]]});
