// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-25,20,{"coast":[[-482300,420000,38,-19,186,-8,48,27],[-481120,420000,301,-76,208,-120,162,1,243,119,186,-116,20,19],[-480000,419997,-9,3]],"land":[[-482300,420000,38,-19,186,-8,48,27,908,0,301,-76,208,-120,162,1,243,119,186,-116,20,19,0,170,-9,3]]});
