// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,22,17,{"border":[[445197,347711,-2332,1118,235,327,1117,1157,1280,1664,1180,1940,1584,4798,187,1285],[445197,347711,2238,-1024,1023,-110,255,-129,1243,-1393,1056,-1472,910,-896,617,-1105,158,-403,5,-335,-252,-701,-18,-143],[443211,340000,1986,7711]],"land":[[460000,340000,0,20000,-20000,0,0,-20000]]});
