// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,13,{"coast":[[520000,260772,220,168,486,-168,244,37,90,200,237,-297,447,-317,0,-395]],"land":[[540000,260000,0,20000,0,-20000,-18276,0,0,395,-447,317,-237,297,-90,-200,-244,-37,-486,168,-220,-168,0,-772]]});
