// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-64,29,{"coast":[[-1271036,591114,322,-16,138,77,-35,91,-120,40,-180,-22,-32,-38,192,-101,-285,-31],[-1274002,585549,0,149,149,0,0,-149,-149,0]],"land":[[-1271036,591114,322,-16,138,77,-35,91,-120,40,-180,-22,-32,-38,192,-101],[-1274002,585549,149,0,0,149,-149,0]]});
