// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,15,17,{"border":[[300000,349087,1244,-889,1049,-489,1467,-559,1398,-978,1118,-1258,979,-490,1188,-279,1537,-70,1678,-350,1887,-838,-140,-1258,489,-419,559,-769,-318,-441]],"county":[[300000,346374,2293,1335]],"land":[[320000,340000,0,20000,-20000,0,0,-20000]]});
