// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-1,34,{"coast":[[-18326,700000,-109,-71,-375,-444,-178,-103,-842,-84,-170,21]],"land":[[-20000,700000,0,-681,170,-21,842,84,178,103,375,444,109,71]]});
