// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,-10,6,{"coast":[[-543713,360000,-217,129,-269,574,147,-19,408,-331,323,-353],[-541665,360000,83,36,45,89,108,-41,-42,-84]],"land":[[-541471,360000,42,84,-108,41,-45,-89,-83,-36,-1656,0,-323,353,-408,331,-147,19,269,-574,217,-129]],"rivers":[[-543639,360000,-366,443,-131,274,0,-69]]});
