// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-67,20,{"coast":[[-1330021,400000,36,29,27,-11,1,-18],[-1330020,400000,-1,0]],"land":[[-1330021,400000,1,0,63,0,-1,18,-27,11]]});
