// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,20,24,{"county":[[416737,495716,-1199,4284],[420000,495594,-3263,122],[409784,480000,493,361,881,952,2261,5249,171,289,939,719,1783,506,49,303,-218,1613,594,5724]],"land":[[420000,480000,0,20000,-20000,0,0,-20000]]});
