// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,8,24,{"coast":[[179237,500000,763,-884]],"land":[[180000,480000,0,20000,-763,0,763,-884]]});
