// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,39,20,{"county":[[780293,403180,444,-155,241,-187,203,-249,159,-373,11,-264,-73,-238,-260,-410,-142,-406,187,-517,315,-381],[780000,403119,293,61]],"land":[[800000,400000,0,20000,-20000,0,0,-20000]]});
