// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,6,5,{"land":[[420000,300000,0,60000,-60000,0,0,-60000]]});
