// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,23,23,{"county":[[469975,474996,-3394,1183,-4088,2702,-2493,720],[469975,474996,2396,-1570,7629,-3421],[469975,474996,4,5004]],"land":[[480000,460000,0,20000,-20000,0,0,-20000]]});
