// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,14,19,{"border":[[280000,387040,14840,8727,5160,3182]],"county":[[300000,390740,-6615,4171]],"land":[[300000,380000,0,20000,-20000,0,0,-20000]]});
