// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,43,23,{"border":[[869786,460044,7515,16957,-86,17,147,90,548,80,106,138,1235,2674],[869786,460044,131,-44],[860000,461361,9786,-1317]],"land":[[880000,460000,0,20000,-20000,0,0,-20000]]});
