// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-17,-10,{"coast":[[-340000,-180424,1,1,236,158,-86,265],[-335867,-180000,530,-96,3320,96]],"land":[[-340000,-180000,0,-424,1,1,236,158,-86,265,3982,0,530,-96,3320,96]]});
