// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,37,26,{"land":[[760000,520000,0,20000,-20000,0,0,-20000]],"rivers":[[754622,540000,200,-338,415,-365,500,-245,981,-181,942,-274,303,-423,616,-514,117,-261,-14,-369,145,-221,495,-334,148,-221,-86,-405,94,-361,-100,-788,211,-946,-14,-729,74,-142,351,-123],[742664,530251,-1304,348,-593,236,-335,58,-432,-37]]});
