// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,25,22,{"border":[[506561,460000,799,-9035,312,-785,2031,-3543,-21,-165,-142,-218,-2845,-2973,-993,-800,-260,-471,-82,-451,83,-462,247,-386,403,-218,-337,-493]],"land":[[520000,440000,0,20000,-20000,0,0,-20000]]});
