// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,27,-5,{"coast":[[540000,-93785,266,55,204,217,267,39,1214,-216,-73,-68,471,-233,19,-195,466,-254,-34,-168,174,-203,-466,-84,-905,-365,-455,-13,-882,145,-266,-41]],"land":[[540000,-95169,266,41,882,-145,455,13,905,365,466,84,-174,203,34,168,-466,254,-19,195,-471,233,73,68,-1214,216,-267,-39,-204,-217,-266,-55]]});
