// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,5,7,{"border":[[332431,420000,27569,18025]],"land":[[360000,420000,0,60000,-60000,0,0,-60000]],"rivers":[[333398,480000,271,-101,921,-149,429,100,549,-26,546,83,545,-123,335,35,508,-101,988,-393,517,30,146,90,338,481,134,74],[340227,480000,409,-106,199,106],[341622,480000,348,-139,183,139]]});
