// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-3,36,{"land":[[-40000,720000,0,20000,-20000,0,0,-20000]],"rivers":[[-49233,740000,269,-255,70,-152,130,-498,-220,-607,20,-182,133,-127,870,-108,1060,-247,93,-124,30,-257,-146,-666,15,-190,106,-89,747,-79,2022,-1078,412,-51,366,216,374,100,157,161,207,541,198,183,107,283,489,47,270,224,1165,287,289,181]]});
