// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,9,6,{"border":[[599812,420000,0,-60000]],"land":[[600000,360000,0,60000,-60000,0,0,-60000]]});
