// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,3,-9,{"coast":[[80000,-172061,-20000,468],[60000,-169999,2148,-1,1157,-139,1154,55,1588,-234,602,-5,889,94,519,-57,2565,35,1188,-310,570,-63,7620,181]],"land":[[60000,-160000,0,-20000,20000,0,0,7939,-20000,468,0,1594,2148,-1,1157,-139,1154,55,1588,-234,602,-5,889,94,519,-57,2565,35,1188,-310,570,-63,7620,181,0,10443]]});
