// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-29,33,{"coast":[[-560685,660000,-913,302,-1275,-133,-1124,16,-211,-67,-124,-118]],"land":[[-560685,660000,-913,302,-1275,-133,-1124,16,-211,-67,-124,-118]]});
