// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,25,{"county":[[520058,518177,539,117,720,266],[520000,518209,58,-32],[521317,518560,704,-1070,-51,-2496,321,-1959,91,-241,3132,-995,2900,-11799],[521317,518560,-590,800,-705,640]],"land":[[540000,500000,0,20000,-20000,0,0,-20000]]});
