// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,34,22,{"land":[[700000,440000,0,20000,-20000,0,0,-20000]],"rivers":[[685795,460000,-23,-1414,-156,-376,-277,-280,-1091,-621,-64,-403,-269,-465,-119,-673,-290,-205,-663,-325,-2266,-530,-411,131,-166,133]]});
