// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,30,{"coast":[[820000,615740,129,-151,4764,-4952,887,-1236,3705,-3972,1072,-1558,1467,-2960,675,-911]],"land":[[832699,600000,-675,911,-1467,2960,-1072,1558,-3705,3972,-887,1236,-4764,4952,-129,151,0,-15740]]});
