// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,7,7,{"border":[[420000,445222,205,-176,4622,-3772,36086,-21274]],"land":[[480000,420000,0,60000,-60000,0,0,-60000]]});
