// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,40,29,{"border":[[800226,600000,9134,-9967,4879,-5000,5219,-5033]],"county":[[810400,599700,-3300,-799,-400,-800,-1515,-3507],[812186,600000,114,-799],[812300,599201,-1900,499]],"land":[[820000,580000,0,20000,-20000,0,0,-20000]]});
