// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,24,19,{"county":[[490427,380000,28,122,-79,1313,435,741,536,552,115,560,-607,1137,-1135,960,-397,1133,21,1013],[500000,381871,-260,60,-1464,490,-4032,3816,-2914,1086,-1985,227],[489345,387550,-1,-19],[489344,387531,-2651,872,-1874,417,-718,580,-1018,1150,-1029,682,-2054,132]],"land":[[500000,380000,0,20000,-20000,0,0,-20000]]});
