// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,48,10,{"border":[[960000,205999,363,173,258,208,181,265,129,761,98,233,588,680,2244,1747,5996,5001,404,127,4516,-605,5223,-618]],"land":[[980000,200000,0,20000,-20000,0,0,-20000]]});
