// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-5,36,{"land":[[-80000,720000,0,20000,-20000,0,0,-20000]],"rivers":[[-100000,724824,917,-379,146,-304,240,8,111,-218,421,-292,269,131,358,-114,397,324,174,-70,274,-578,446,-306,68,67,409,-621,475,-289,298,-396,490,-309,512,-214,280,-20,330,-144,322,0,89,-66,392,-975,182,-59]]});
