// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-6,37,{"coast":[[-120000,750000,20000,0]],"land":[[-100000,740000,0,10000,-20000,0,0,-10000]],"rivers":[[-108548,749672,-101,-712,67,-644,102,-319,166,-244,-133,-371,75,-2047,300,-355,106,-367,-94,-531,-221,-320,-368,-186,-311,-291,-113,-336,14,-874,-69,-158,69,-123,-248,-389,-26,-920,-87,-349,-64,-136]]});
