// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,45,11,{"border":[[909784,236783,8151,334,2065,326],[920000,234213,-395,-685,115,-1013,-222,-790,3,-386,283,-290,216,-76],[909784,236783,-10,-16783],[900000,232544,1000,1014,1284,1714,308,281,1134,691,401,677,376,290,590,200,1262,-55,589,-172,929,-101,893,-328,1018,28]],"land":[[920000,220000,0,20000,-20000,0,0,-20000]]});
