// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,36,37,{"coast":[[720000,750000,20000,0]],"land":[[740000,740000,0,10000,-20000,0,0,-10000]],"rivers":[[720000,742638,220,-52,-38,-307,96,-78,905,-449,434,-73,293,-125,463,-374,-57,-205,405,-75],[722721,740900,204,-205,34,-117,-108,-183,196,-382,-3,-13]]});
