// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,22,20,{"border":[[450283,400000,37,1437,125,267,1489,797,188,270,175,930,125,348,1496,1151,187,67,397,-36,2272,-770,217,-22,3009,900]],"land":[[460000,400000,0,20000,-20000,0,0,-20000]]});
