// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-12,32,{"land":[[-220000,640000,0,20000,-20000,0,0,-20000]],"rivers":[[-221419,640000,178,237,304,236,289,68,273,191,375,701],[-220000,658345,-102,101,-41,263,61,474,-123,309,-391,508]]});
