// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,20,22,{"border":[[400000,457099,7493,-1436,450,-161,433,-288,11624,-9992]],"land":[[420000,440000,0,20000,-20000,0,0,-20000]]});
