// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-31,-9,{"coast":[[-602431,-160000,113,-153,640,-138,1291,-61,387,-81]],"land":[[-602431,-160000,113,-153,640,-138,1291,-61,387,-81,0,433]]});
