// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,50,-8,{"coast":[[1003302,-160000,-240,46,825,92,343,137,427,376,-40,94,-159,59,-2912,697,-763,85,-518,265,-265,60]],"land":[[1000000,-160000,3302,0,-240,46,825,92,343,137,427,376,-40,94,-159,59,-2912,697,-763,85,-518,265,-265,60]]});
