// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-61,35,{"coast":[[-1209335,706091,185,0,157,77,197,-73,145,57,53,99,-466,102,-161,-53,-110,-209]],"land":[[-1209335,706091,185,0,157,77,197,-73,145,57,53,99,-466,102,-161,-53]]});
