// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,21,19,{"county":[[420000,395033,1384,1501,253,381,70,221,-67,381,-547,748,-235,643,3,1077,4,15]],"land":[[440000,380000,0,20000,-20000,0,0,-20000]]});
