// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,18,18,{"county":[[370830,360000,511,5085,-133,2014,-553,2168,-1070,10733]],"land":[[380000,360000,0,20000,-20000,0,0,-20000]]});
