// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,27,37,{"coast":[[540000,750000,20000,0]],"land":[[560000,740000,0,10000,-20000,0,0,-10000]],"rivers":[[544706,749432,-158,-888,66,-886,417,-793,233,-254,32,-208,-166,-555,-306,-485,-114,-374,-10,-1379,50,-233,-185,-639,-292,-663,24,-704,-256,-603,-247,-276,-181,-341,-44,-151]]});
