// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,29,21,{"border":[[599812,430046,0,-10046],[599809,440000,3,-9954],[599812,430046,188,1]],"land":[[600000,420000,0,20000,-20000,0,0,-20000]]});
