// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,21,22,{"border":[[420000,445222,205,-176,4622,-3772,2162,-1274]],"land":[[440000,440000,0,20000,-20000,0,0,-20000]]});
