// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-7,37,{"coast":[[-140000,750000,20000,0]],"land":[[-120000,740000,0,10000,-20000,0,0,-10000]],"rivers":[[-131882,740000,-23,151,-881,1152,-782,1545,-124,423,-107,2160,-273,852,41,159,300,355,55,190,13,666,-96,204,28,107,273,204,196,396,-214,449,-301,242,99,417,210,281]]});
