// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-8,30,{"coast":[[-159975,620000,-25,-88]],"land":[[-160000,620000,0,-88,25,88]]});
