// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,50,17,{"border":[[1000000,354588,364,10,11592,-2951,796,-499,472,-613,181,-101,-801,-665,-352,-213,-59,-135,170,-537,646,-1140,44,-192,-23,-605,188,-1321,-80,-409,-319,-398,-170,-397,31,-436,983,-3215,91,-138,169,-79,1577,-324,246,-230]],"land":[[1020000,340000,0,20000,-20000,0,0,-20000]]});
