// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,28,35,{"land":[[580000,700000,0,20000,-20000,0,0,-20000]],"rivers":[[565742,720000,-564,-749,-957,-825,-596,-291,-173,-267,-608,-330,-571,-538,-425,-143,-766,-595,-579,-545,-164,29,-269,-196,-70,-21],[560000,703548,304,-180,153,-307,346,-257,49,-275,-130,-341,130,-450,0,-848,142,-722,-28,-168]]});
