// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,5,23,{"coast":[[100000,478657,82,34,205,236,-77,204,-210,220]],"county":[[100000,479126,133,85]],"land":[[100000,478657,82,34,205,236,-77,204,-210,220]]});
