// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,13,17,{"border":[[267583,360000,594,-355,1126,-438,334,-206,913,-763,1059,-628,611,-503,480,-219,764,-650,341,-132,1134,92,428,-89,1137,57,908,-839,1119,-419,768,-70,701,44]],"land":[[280000,340000,0,20000,-20000,0,0,-20000]],"rivers":[[264500,344667,-1376,122,-1222,496,-1319,402,-583,-55]]});
