// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,35,37,{"coast":[[700000,750000,20000,0]],"land":[[720000,740000,0,10000,-20000,0,0,-10000]],"rivers":[[711969,749960,83,-707,177,-351,66,-446,557,-765,689,-342,419,-389,444,-620,88,-251,-4,-449,117,-231,974,-477,573,-35,308,-132,420,-64,453,-339,487,-36,163,-75,1382,-1173,432,-239,149,-188,54,-13]]});
