// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,5,6,{"border":[[300000,400050,1784,-1],[301784,400049,3056,1911,27591,18040],[300000,398949,1784,1100]],"land":[[360000,360000,0,60000,-60000,0,0,-60000]]});
