// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,48,16,{"border":[[968191,340000,73,-150,-49,-395,-297,-644,-41,-397,-450,-809,65,-629,-69,-185,-554,-523,-257,-87,-6612,-827]],"land":[[980000,320000,0,20000,-20000,0,0,-20000]],"rivers":[[966041,337956,327,867,302,517,237,280,715,380]]});
