// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,30,15,{"coast":[[600000,300646,191,38,583,-131,304,68,211,-136,220,-42,723,15,808,-306,437,-67,675,-22,910,91,506,-154],[611045,300000,7,7,278,0,18,-7]],"land":[[600000,300000,11348,0,-18,7,-278,0,-7,-7,-5477,0,-506,154,-910,-91,-675,22,-437,67,-808,306,-723,-15,-220,42,-211,136,-304,-68,-583,131,-191,-38]]});
