// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,-2,-1,{"coast":[[-60000,-916,-571,-82,-252,-319,-160,18,-245,129,-43,261,61,106,434,126,440,397,269,134,-68,137,11,9]],"land":[[-120000,0,0,-60000,60000,0,0,59084,-571,-82,-252,-319,-160,18,-245,129,-43,261,61,106,434,126,440,397,269,134,-68,137,11,9]]});
