// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,28,17,{"county":[[579689,342006,-1,-2006],[579737,342002,263,94],[579689,342006,48,-4],[577899,342084,-1707,-374,-1074,-645,-553,-993,-93,-72],[579689,342006,-1790,78]],"land":[[580000,340000,0,20000,-20000,0,0,-20000]]});
