// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,-13,9,{"coast":[[-742342,546921,156,263,82,-71,-16,-140,-222,-52]],"land":[[-742342,546921,222,52,16,140,-82,71]]});
