// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,-20,7,{"coast":[[-1200000,452702,219,408,-28,507,357,171,-19,163,445,365,877,391,81,133,-135,371,-149,172,-540,461,-394,208,-433,449,-281,130]],"land":[[-1200000,452702,219,408,-28,507,357,171,-19,163,445,365,877,391,81,133,-135,371,-149,172,-540,461,-394,208,-433,449,-281,130]]});
