// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,29,{"coast":[[832699,600000,590,-797,1191,-1290,1001,-1664,720,-689,266,-360,491,-1073,1543,-2371,1499,-2577]],"county":[[825801,600000,298,-1899,-1399,-3800,-1200,-1800,2500,-5300],[826000,587201,0,-1]],"land":[[840000,580000,0,9179,-1499,2577,-1543,2371,-491,1073,-266,360,-720,689,-1001,1664,-1191,1290,-590,797,-12699,0,0,-20000]]});
