// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-11,35,{"land":[[-200000,700000,0,20000,-20000,0,0,-20000]],"rivers":[[-220000,703722,23,-42,-16,-296,-7,-22],[-220000,702643,56,-96,367,-358,846,-449,162,-159,123,-398,7,-621,393,-562]]});
