// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,23,37,{"coast":[[480000,740222,-76,158,39,558,37,52]],"land":[[480000,740000,0,990,-37,-52,-39,-558,76,-158]]});
