// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,50,-9,{"coast":[[1000000,-161727,2298,360,1455,764,610,232,137,143,-1198,228]],"land":[[1000000,-160000,0,-1727,2298,360,1455,764,610,232,137,143,-1198,228]]});
