// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,-8,-4,{"coast":[[-423644,-180000,294,-133,2010,-237,-186,122,-224,15,446,127,1304,-36]],"land":[[-423644,-180000,294,-133,2010,-237,-186,122,-224,15,446,127,1304,-36,0,142]]});
