// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,44,18,{"coast":[[880000,378622,287,337,433,72,3189,969]],"land":[[900000,360000,0,20000,-16091,0,-3189,-969,-433,-72,-287,-337,0,1378,0,-20000]]});
