// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-16,35,{"land":[[-300000,700000,0,20000,-20000,0,0,-20000]],"rivers":[[-320000,701047,272,26,133,-28,288,-254,405,-190,178,-176,153,-425],[-308804,704351,795,-373,2050,-203,1168,-284,759,70,719,235,518,-8,516,-106,1114,-371,969,854,196,378]]});
