// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-15,37,{"coast":[[-300000,750000,20000,0]],"land":[[-280000,740000,0,10000,-20000,0,0,-10000]],"rivers":[[-300000,745886,22,8,580,84,95,-22,488,-456,447,-103,160,-197,69,-205,-55,-457,-152,-427,-5,-188,120,-174,637,-19,219,-86,205,-410,272,-307,764,-511,239,-554,772,-340,802,382,645,-110,223,-210,551,-1110,294,-326,202,-61,559,-4,260,-83]]});
