// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,29,24,{"border":[[580000,493913,45,-27,640,-753,261,-176,722,-86,1538,316,752,-70,1313,-469,656,-138,1148,1,1216,179,1164,388,271,11,118,-301,-10,-12788]],"land":[[600000,480000,0,20000,-20000,0,0,-20000]]});
