// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,19,23,{"border":[[382804,460000,45,43,335,180,403,8,1217,-231],[392356,480000,-65,-20000]],"land":[[400000,460000,0,20000,-20000,0,0,-20000]]});
