// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,12,-3,{"coast":[[258826,-58749,77,138,436,288,-136,199,253,54,544,-30],[260000,-59005,-466,180,-708,76]],"land":[[258826,-58749,708,-76,466,-180,0,905,-544,30,-253,-54,136,-199,-436,-288]]});
