// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-38,22,{"coast":[[-758362,457164,219,-508,0,-136,266,341,-364,276,-61,130,-60,-103]],"land":[[-758362,457164,219,-508,0,-136,266,341,-364,276,-61,130]]});
