// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,20,23,{"county":[[400000,472643,939,761,1320,1736,222,201,5552,3380,1751,1279]],"land":[[420000,460000,0,20000,-20000,0,0,-20000]]});
