// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,22,34,{"coast":[[452895,680000,575,445,1056,888,965,1058,39,196,824,550,135,380,-105,552,80,450,1613,1110,1561,1286,208,231,52,428,102,230]],"land":[[460000,680000,0,7804,-102,-230,-52,-428,-208,-231,-1561,-1286,-1613,-1110,-80,-450,105,-552,-135,-380,-824,-550,-39,-196,-965,-1058,-1056,-888,-575,-445]]});
