// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,42,15,{"land":[[860000,300000,0,20000,-20000,0,0,-20000]],"rivers":[[848257,320000,-23,-15,-382,-32,-68,47],[841105,311021,240,275,92,267,567,491,247,367,203,181,403,626,-25,179,-141,141,-208,56,-1005,-262,-278,-138,-265,-3,-556,159,-379,182],[840000,314253,457,60,155,387,42,472,-109,141,-545,329]]});
