// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,21,29,{"border":[[436869,600000,117,-178,303,-767,194,-297,100,-107,334,-118,72,-129,268,-1359,-104,-480,345,-889,-55,-600,62,-216,490,-570,44,-241,-102,-267,-613,-564,-131,-253,429,-488,44,-252,-195,-333,-19,-202,107,-165,353,-236,305,-334,433,109,177,-22,111,-483,62,-32]],"land":[[440000,580000,0,20000,-20000,0,0,-20000]]});
