// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,41,21,{"county":[[832125,420000,-1983,14998,-683,5002]],"land":[[840000,420000,0,20000,-20000,0,0,-20000]]});
