// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,-5,{"coast":[[537898,-94782,235,98,522,380,664,251,312,192,369,76],[540000,-95169,-184,-29,-1068,36,-543,121,-307,259]],"land":[[537898,-94782,307,-259,543,-121,1068,-36,184,29,0,1384,-369,-76,-312,-192,-664,-251,-522,-380]]});
