// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,47,20,{"coast":[[941621,420000,-742,-484,-142,-448,-636,-601,-84,-591,-17,-18]],"land":[[940000,400000,0,17858,17,18,84,591,636,601,142,448,742,484,-1621,0]]});
