// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,0,{"coast":[[1050000,0,0,20000]],"county":[[1040519,5266,278,122,380,59],[1040000,5316,148,-34,371,-16],[1042136,5281,305,61,927,479,315,226,213,68],[1041177,5447,959,-166],[1046931,6000,398,58,401,177,523,355,1746,251],[1043896,6115,3035,-115]],"land":[[1040000,20000,0,-20000,10000,0,0,20000]]});
