// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,0,-2,{"county":[[15021,-60000,770,0],[0,-60000,15021,0]],"land":[[0,-60000,0,-60000,60000,0,0,60000]]});
