// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,15,{"border":[[1044717,320000,160,-284,265,-283,333,-183,932,-92,271,72,182,-38,470,-285,388,-55,669,281,422,-25,749,-385,442,-16,0,-6124,-425,-110,-262,-537,-325,-451,-134,-380,-382,-374,-61,-149,309,-297,6,-457,167,-140,798,-145,309,17]],"land":[[1050000,320000,-10000,0,0,-20000,10000,0,0,9560]]});
