// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,42,29,{"coast":[[840000,589179,361,-621,352,-757,143,-875,-115,-634,6,-445,1232,-2583,494,-1370,459,-703,607,-1191]],"land":[[843539,580000,-607,1191,-459,703,-494,1370,-1232,2583,-6,445,115,634,-143,875,-352,757,-361,621,0,-9179]]});
