// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,29,37,{"land":[[600000,740000,0,10000,-20000,0,0,-10000]],"rivers":[[590866,749624,27,-247,105,-142,-185,-140,-559,-169,-145,-262,16,-364,265,-609,655,-552,56,-116,115,-710,0,-779,341,-716,-134,-1125,-275,-316,-516,-416,-135,-230,-305,-179,-303,-592,-626,-723,-169,-125,-684,-85,-180,-89,-452,-433,-63,-213,32,-292]]});
