// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,20,18,{"county":[[409527,365092,4975,3491,607,518,335,805,222,1213,-400,300,-2688,926,-2478,2113,-1376,974,-349,505,-218,849,247,1187,670,2027],[420000,361403,-628,-87],[419372,361316,-1498,1,-3665,1370,-4682,2405],[400000,365321,9527,-229]],"land":[[420000,360000,0,20000,-20000,0,0,-20000]]});
