// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-29,22,{"coast":[[-562001,460000,385,-163,820,-710,659,-260,137,-87]],"land":[[-560000,460000,-2001,0,385,-163,820,-710,659,-260,137,-87]]});
