// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,31,18,{"county":[[640000,370074,-1539,718,-712,476,-502,670,-715,1383],[640000,360036,-990,875,-2018,1338,-7930,1822,-743,264,-473,459,-275,370,-4323,8157],[640000,373321,-3468,0],[636532,373321,-13284,0],[620000,373323,3248,-2]],"land":[[640000,360000,0,20000,-20000,0,0,-20000]]});
