// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,31,27,{"border":[[620000,554202,804,-270,2588,-60,459,80,1430,-6,812,102,322,-67,1281,186,988,-52,267,-69,1020,2105,480,535,7987,69,-123,-247,-28,-783,206,-384,645,-631,862,-669]],"land":[[640000,540000,0,20000,-20000,0,0,-20000]]});
