// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,14,20,{"border":[[286404,420000,-2335,-19941,15931,-9]],"county":[[280000,410418,4937,-3178],[285694,420000,590,-1240]],"land":[[300000,400000,0,20000,-20000,0,0,-20000]]});
