// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,23,20,{"border":[[469689,414826,10311,2301],[460000,405339,5086,1523,328,163,257,307,4018,7494],[460913,420000,8776,-5174]],"land":[[480000,400000,0,20000,-20000,0,0,-20000]]});
