// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,48,7,{"border":[[960000,142979,3721,-804,319,-201,229,-305,149,-419,149,-900,102,-350]],"lakeEdge":[[966329,140000,-38,490,-156,91,-965,100,-171,-76,-21,-86,265,-114,-203,-183,-86,-222]],"lakes":[[964954,140000,1375,0,-38,490,-156,91,-965,100,-171,-76,-21,-86,265,-114,-203,-183]],"land":[[980000,140000,0,20000,-20000,0,0,-20000]]});
