// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-63,32,{"coast":[[-1250300,653762,52,126,124,-67,35,-96,-211,37]],"land":[[-1250300,653762,211,-37,-35,96,-124,67]]});
