// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,34,-8,{"coast":[[680000,-152190,742,-12,244,-75,2000,-204,3418,273,-442,176,-527,81,-5116,240,-319,60]],"land":[[680000,-152190,742,-12,244,-75,2000,-204,3418,273,-442,176,-527,81,-5116,240,-319,60]]});
