// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-67,19,{"coast":[[-1329957,400000,1,-19,-21,-25,-43,44]],"land":[[-1330020,400000,43,-44,21,25,-1,19]]});
