// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,25,19,{"county":[[512742,380000,-51,707,93,831,443,534,1973,913,551,706,-71,1028,527,1023,1069,996,1554,921,575,707,595,115],[509733,380000,-2123,521,-2939,501,-1891,211,-2780,638]],"land":[[520000,380000,0,20000,-20000,0,0,-20000]]});
