// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-18,27,{"land":[[-340000,540000,0,20000,-20000,0,0,-20000]],"rivers":[[-342605,547525,299,314,148,778,207,382,118,78,505,61,83,58,116,452,234,359,122,685,484,491,289,479]]});
