// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,21,25,{"border":[[420768,520000,133,-64,473,-408,608,-702,223,-42,1043,188,359,2,313,-99,3636,-2146,341,-149,343,-33,2535,353,276,103,963,733,584,212,1454,1343,138,42,270,-120,367,-29,508,170,633,532,78,114]],"land":[[440000,500000,0,20000,-20000,0,0,-20000]]});
