// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(2,8,6,{"border":[[499895,420000,9751,-4422,205,-25,9006,4447],[480000,417127,4823,1076,1173,607,1460,1190]],"land":[[540000,360000,0,60000,-60000,0,0,-60000]]});
