// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,20,11,{"coast":[[411661,220000,1,3,363,126,413,-129]],"land":[[411661,220000,777,0,-413,129,-363,-126]]});
