// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,26,21,{"border":[[520000,420564,20000,9877]],"land":[[540000,420000,0,20000,-20000,0,0,-20000]]});
