// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,2,-3,{"coast":[[60000,-54847,-360,50,-405,167,-1221,-57,-239,71,-116,135,6,63,539,204,-23,89,-243,184,956,0,1106,-218]],"land":[[40000,-40000,0,-20000,20000,0,0,5153,-360,50,-405,167,-1221,-57,-239,71,-116,135,6,63,539,204,-23,89,-243,184,956,0,1106,-218,0,14159]]});
