// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,52,3,{"coast":[[1050000,60000,0,20000]],"land":[[1040000,80000,0,-20000,10000,0,0,20000]],"rivers":[[1049929,70097,-365,-242,-218,-41,-851,346,-824,-50,-362,62,25,261,-281,66,-471,-148,-1791,-254,-69,-105,98,-278,-1020,-15,-171,126,122,131,-122,141,-513,-136,-511,199,-247,-118,-340,-446,-263,-81,-605,149,-806,499,-344,-65]]});
