// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,13,23,{"county":[[266672,460000,-6672,14028],[264017,476494,3091,3276,-217,230],[260000,476991,4017,-497]],"land":[[280000,460000,0,20000,-20000,0,0,-20000]]});
