// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-16,-3,{"coast":[[-320000,-41779,225,10,1956,438,396,-38,735,-477,148,-152,46,-224,-217,-422,-198,-185,-478,-187,-493,-384,-2120,-600]],"land":[[-320000,-40000,0,-4000,2120,600,493,384,478,187,198,185,217,422,-46,224,-148,152,-735,477,-396,38,-1956,-438,-225,-10]]});
