// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,30,27,{"border":[[600000,549765,290,-685,-154,-571,35,-189,598,-1189,437,-192,363,-1,759,-161,459,103,487,-46,998,-275,636,-15,1325,-403,824,-101,483,7,745,-242,146,17,505,665,118,1700,503,344,551,242,656,1050,262,299,769,288,3774,4385,688,398,686,38,3057,-1029]],"land":[[620000,540000,0,20000,-20000,0,0,-20000]]});
