// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-18,36,{"land":[[-340000,720000,0,20000,-20000,0,0,-20000]],"rivers":[[-345737,740000,84,-117,558,117],[-344518,740000,32,-18,137,-477,242,-175,292,-342,649,-163,420,-539,892,-123,-116,-162,32,-74,804,-352,453,42,205,-136,352,-72,124,52]]});
