// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-19,29,{"border":[[-369292,580000,810,161,156,-25,196,-136],[-362791,580000,36,156,135,57,488,12,292,149,177,-55,303,-240,705,76,542,-64,113,-42]],"land":[[-360000,580000,0,20000,-20000,0,0,-20000]],"rivers":[[-360100,600000,100,-237]]});
