// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,27,22,{"border":[[559358,440000,642,317]],"county":[[558826,440000,-8783,17205,699,2795]],"land":[[560000,440000,0,20000,-20000,0,0,-20000]]});
