// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,35,32,{"land":[[720000,640000,0,20000,-20000,0,0,-20000]],"rivers":[[717035,653501,85,-123,199,-88,802,-235,385,130,789,-130,349,80,139,93,202,814,15,21]]});
