// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-42,18,{"coast":[[-832273,360000,-18,40,77,367,-44,442,-256,306,-190,-17,-188,73,4,108,-96,-87,37,-118,111,-40,-139,-383,35,-172,-60,-197,-160,-139,117,-163,-9,-20]],"land":[[-832273,360000,-18,40,77,367,-44,442,-256,306,-190,-17,-188,73,4,108,-96,-87,37,-118,111,-40,-139,-383,35,-172,-60,-197,-160,-139,117,-163,-9,-20]]});
