// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,36,17,{"border":[[720000,350904,4702,-850,215,-166,1559,-3197,231,-167,3107,-1512,-4942,-5012]],"land":[[740000,340000,0,20000,-20000,0,0,-20000]]});
