// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,20,19,{"county":[[409074,380000,509,1539,517,511,1963,1353,366,322,190,290,94,280,41,325,-55,254,-905,2005,-63,534,57,271,165,147,1120,516,2305,2704,1741,732,2467,619,147,262,111,439,111,1881,45,49]],"land":[[420000,380000,0,20000,-20000,0,0,-20000]]});
