// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,-62,-4,{"coast":[[-1223627,-60000,307,-122,874,-397,1217,-727,573,-293,639,-376,17,-8]],"land":[[-1223627,-60000,307,-122,874,-397,1217,-727,573,-293,639,-376,17,-8,0,1923]]});
