// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,39,32,{"coast":[[780000,648761,902,-995,1953,-1916,1821,-2056,1913,-1843,446,-356,307,-145,477,-666,379,-278,945,-506]],"land":[[789143,640000,-945,506,-379,278,-477,666,-307,145,-446,356,-1913,1843,-1821,2056,-1953,1916,-902,995,0,-8761]],"rivers":[[783341,640000,-93,185,-206,139,-122,205,-81,239,-74,1010,-138,322,-295,-82]]});
