// Generated by pipeline/basemap/build_basemap.py -- do not edit. Sources: US Census Bureau
// cartographic boundary files (counties 1:500k, 2023) and Natural Earth 1:10m (public domain).
BASEMAP_TILE(3,8,16,{"coast":[[177479,321855,109,354,605,531,377,204,1430,502],[180000,321762,-143,68,-537,28,-639,-249,-342,-294,-188,-57,-154,57,-247,292,-214,107,-57,141]],"land":[[177479,321855,57,-141,214,-107,247,-292,154,-57,188,57,342,294,639,249,537,-28,143,-68,0,1684,-1430,-502,-377,-204,-605,-531]]});
